version: '3'

dotenv: ['.env', '../.env', '../../.env']

tasks:
  default:
    cmds:
      - task: run

  # ============================================================================
  # MAIN AUTOMATION
  # ============================================================================
  run:
    desc: Run the main automation client
    dir: probe
    vars:
      DRY_RUN: '{{.DRY_RUN | default "true"}}'
      STEP: '{{.STEP | default "true"}}'
      MOCK_PERMISSIONS: '{{.METRC_USE_MOCK_PERMISSIONS | default "false"}}'
    cmds:
      - go run . -dry-run={{.DRY_RUN}} -step={{.STEP}} -mock-permissions={{.MOCK_PERMISSIONS}}

  setup-sandbox:
    desc: Setup a new Integrator Sandbox User (requires METRC_VENDOR_API_KEY)
    dir: probe
    vars:
        # Default to empty if not provided; API will create new user if empty
        USER_KEY: '{{.USER_KEY | default ""}}' 
    cmds:
      - |
        echo "Setting up Sandbox User..."
        if [ -z "$METRC_VENDOR_API_KEY" ]; then
          echo "Error: METRC_VENDOR_API_KEY is not set. Please set it in your .env file."
          exit 1
        fi
        
        # Fallback to env var if template var is empty
        TARGET_USER_KEY="{{.USER_KEY}}"
        if [ -z "$TARGET_USER_KEY" ]; then
             TARGET_USER_KEY="$METRC_USER_API_KEY"
        fi

        URL="${METRC_BASE_URL:-https://sandbox.metrc.com}/sandbox/v2/integrator/setup"
        if [ ! -z "$TARGET_USER_KEY" ]; then
             URL="$URL?userKey=$TARGET_USER_KEY"
             echo "Validating User Key: $TARGET_USER_KEY"
        else
             echo "Requesting new Integrator Sandbox setup..."
        fi

        curl -s -X POST "$URL" \
          -H "x-metrc-key: $METRC_VENDOR_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{}' \
          -v

  # ============================================================================
  # CODE GENERATION
  # ============================================================================
  gen:all:
    desc: Run all generation tasks (specs, client, models, sdks)
    cmds:
      - task: gen:spec
      - task: gen:schema
      - task: gen:internal
      - task: gen:sdks

  gen:spec:
    desc: Generate Bruno specs from Metrc documentation
    dir: tools
    cmds:
      - go run . gen specs {{.CLI_ARGS}}

  gen:schema:
    desc: Generate JSON schemas from captured and manual responses
    dir: tools
    cmds:
      - go run . gen schemas {{.CLI_ARGS}}

  gen:internal:
    desc: Generate internal schemas and models for the automation engine
    dir: tools
    cmds:
      - go run . gen internal

  gen:sdks:
    desc: Generate SDKs for all supported languages
    dir: tools
    cmds:
      - go run . gen sdks



  # ============================================================================
  # MOCK SERVER
  # ============================================================================
  mock:start:
    desc: Start the mock server in STATEFUL mode (default, in-memory CRUD)
    dir: mockserver
    vars:
      PORT: '{{.PORT | default "8080"}}'
      SCENARIO: '{{.SCENARIO | default "default"}}'
    cmds:
      - go run . --port {{.PORT}} --scenario {{.SCENARIO}} --stateful=true

  mock:stateless:
    desc: Start in STATELESS mode (returns fixed JSON from specs/source/captured/responses/)
    dir: mockserver
    vars:
      PORT: '{{.PORT | default "8080"}}'
    cmds:
      - go run . --port {{.PORT}} --stateful=false --responses ../specs/source/captured/responses

  mock:ratelimit:
    desc: Start stateful mock with aggressive rate limiting (5 req/sec)
    dir: mockserver
    cmds:
      - go run . --scenario aggressive --stateful=true

  mock:noauth:
    desc: Start stateful mock without auth requirement
    dir: mockserver
    cmds:
      - go run . --auth=false --stateful=true

  mock:gen:
    desc: Generate mock server handlers from Bruno specs
    dir: tools
    cmds:
      - go run . mock gen -out ../mockserver/pkg/server/handlers/generated.go

  # ============================================================================
  # DATA ANALYSIS
  # ============================================================================
  analyze:
    desc: Analyze facility permissions and group facilities by capability
    dir: tools
    cmds:
      - go run . analyze permissions

  # ============================================================================
  # TESTING
  # ============================================================================
  test:all:
    desc: Run integration tests for all SDKs
    deps: [test:csharp, test:go, test:typescript, test:python, test:java, test:kotlin, test:rust]

  test:csharp:
    desc: Run C# tests
    cmds:
      - echo "--- Testing C# SDK ---"
      - dotnet test sdks/thunkmetrc-cs/ThunkMetrc.Test/ThunkMetrc.Test.csproj

  test:go:
    desc: Run Go tests
    cmds:
      - echo "--- Testing Go SDK ---"
      - cmd: cd sdks/thunkmetrc-go/client && go test ./... || echo "No tests found or failed"
      - cmd: cd sdks/thunkmetrc-go/wrapper && go test ./... || echo "No tests found or failed"
      - cmd: cd sdks/thunkmetrc-go/thunkmetrc && go test ./... || echo "No tests found or failed"

  test:typescript:
    desc: Run TypeScript tests
    dir: sdks/thunkmetrc-ts/thunkmetrc
    cmds:
      - echo "--- Testing TypeScript SDK ---"
      - npm install
      - npm test

  test:python:
    desc: Run Python tests
    dir: sdks/thunkmetrc-py/thunkmetrc
    cmds:
      - echo "--- Testing Python SDK ---"
      - pip install -e ../client -e ../wrapper -e . -q
      - pip install pytest pytest-asyncio python-dotenv -q
      - pytest tests/ -v

  test:java:
    desc: Run Java tests
    cmds:
      - echo "--- Testing Java SDK ---"
      - mvn -f sdks/thunkmetrc-java/client/pom.xml install
      - mvn -f sdks/thunkmetrc-java/wrapper/pom.xml install
      - mvn -f sdks/thunkmetrc-java/thunkmetrc/pom.xml install

  test:kotlin:
    desc: Run Kotlin tests
    cmds:
      - echo "--- Testing Kotlin SDK ---"
      - mvn -f sdks/thunkmetrc-kotlin/client/pom.xml install
      - mvn -f sdks/thunkmetrc-kotlin/wrapper/pom.xml install
      - mvn -f sdks/thunkmetrc-kotlin/thunkmetrc/pom.xml install

  test:rust:
    desc: Run Rust tests
    cmds:
      - echo "--- Testing Rust SDK ---"
      - cargo test --manifest-path sdks/thunkmetrc-rs/Cargo.toml

  # ============================================================================
  # PUBLISHING
  # ============================================================================
  publish:all:
    desc: Publish all SDKs (C#, TS, Py, Java, Rust, Kotlin)
    cmds:
      - task: gen:sdks
      - task: publish:csharp
      - task: publish:typescript
      - task: publish:python
      - task: publish:java
      - task: publish:kotlin
      - task: publish:rust

  build:all:
    desc: Build all SDKs to verify compilation
    deps: [build:csharp, build:typescript, build:python, build:java, build:kotlin, build:rust, build:go]

  build:csharp:
    desc: Build C# SDK
    cmds:
      - dotnet build sdks/thunkmetrc-cs/ThunkMetrc.Client/ThunkMetrc.Client.csproj -c Release
      - dotnet build sdks/thunkmetrc-cs/ThunkMetrc.Wrapper/ThunkMetrc.Wrapper.csproj -c Release

  build:typescript:
    desc: Build TypeScript SDK
    cmds:
      - cmd: cd sdks/thunkmetrc-ts/client && npm install && npm run build
      - cmd: cd sdks/thunkmetrc-ts/wrapper && npm install && npm run build
      - cmd: cd sdks/thunkmetrc-ts/thunkmetrc && npm install && npm run build

  build:python:
    desc: Build Python SDK
    dir: sdks/thunkmetrc-py
    cmds:
      - python -m py_compile client/src/thunkmetrc/client/client.py
      - python -m py_compile wrapper/src/thunkmetrc/wrapper/wrapper.py
      - python -m py_compile thunkmetrc/src/thunkmetrc/inventory_sync.py

  build:java:
    desc: Build Java SDK
    dir: sdks/thunkmetrc-java
    cmds:
      - mvn clean install -f client/pom.xml -DskipTests
      - mvn clean install -f wrapper/pom.xml -DskipTests
      - mvn clean install -f thunkmetrc/pom.xml -DskipTests

  build:kotlin:
    desc: Build Kotlin SDK
    dir: sdks/thunkmetrc-kotlin
    cmds:
      - mvn clean install -f client/pom.xml -DskipTests
      - mvn clean install -f wrapper/pom.xml -DskipTests
      - mvn clean install -f thunkmetrc/pom.xml -DskipTests

  build:rust:
    desc: Build Rust SDK
    dir: sdks/thunkmetrc-rs
    cmds:
      - cargo check

  build:go:
    desc: Build Go SDK
    cmds:
      - cmd: cd sdks/thunkmetrc-go/client && go build ./...
      - cmd: cd sdks/thunkmetrc-go/wrapper && go build ./...
      - cmd: cd sdks/thunkmetrc-go/thunkmetrc && go build ./...

  publish:csharp:
    desc: Publish C# SDK to NuGet
    cmds:
      - dotnet build ./sdks/thunkmetrc-cs/ThunkMetrc.Client/ThunkMetrc.Client.csproj -c Release
      - dotnet pack ./sdks/thunkmetrc-cs/ThunkMetrc.Client/ThunkMetrc.Client.csproj -c Release -o ./out --no-build
      - dotnet build ./sdks/thunkmetrc-cs/ThunkMetrc.Wrapper/ThunkMetrc.Wrapper.csproj -c Release
      - dotnet pack ./sdks/thunkmetrc-cs/ThunkMetrc.Wrapper/ThunkMetrc.Wrapper.csproj -c Release -o ./out --no-build
      - dotnet build ./sdks/thunkmetrc-cs/ThunkMetrc/ThunkMetrc.csproj -c Release
      - dotnet pack ./sdks/thunkmetrc-cs/ThunkMetrc/ThunkMetrc.csproj -c Release -o ./out --no-build
      - dotnet nuget push ./out/*.nupkg -s https://api.nuget.org/v3/index.json -k "${NUGET_API_KEY}" --skip-duplicate

  publish:typescript:
    desc: Publish TypeScript SDK to NPM
    dir: sdks/thunkmetrc-ts/client
    cmds:
      - npm install --no-audit --no-fund
      - npm run build
      - cmd: 'if [ -z "$NPM_TOKEN" ]; then echo "Error: NPM_TOKEN is missing"; exit 1; fi'

      - cmd: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - npm publish --access public
      - cmd: rm .npmrc
      - cmd: cd ../wrapper && npm install && npm run build
      - cmd: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ../wrapper/.npmrc
      - cmd: cd ../wrapper && npm publish --access public
      - cmd: rm ../wrapper/.npmrc
      - cmd: cd ../thunkmetrc && npm install && npm run build
      - cmd: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ../thunkmetrc/.npmrc
      - cmd: cd ../thunkmetrc && npm publish --access public
      - cmd: rm ../thunkmetrc/.npmrc

  publish:python:
    desc: Publish Python SDK to PyPI
    dir: sdks/thunkmetrc-py/client
    cmds:
      - pip install hatch twine
      - hatch build
      - twine upload dist/*
      - cmd: cd ../wrapper && pip install hatch twine && hatch build && twine upload dist/*
      - cmd: cd ../thunkmetrc && pip install hatch twine && hatch build && twine upload dist/*

  publish:rust:
    desc: Publish Rust SDK to crates.io
    dir: sdks/thunkmetrc-rs/client
    cmds:
      - cmd: if [ ! -z "$CARGO_TOKEN" ]; then cargo login $CARGO_TOKEN; fi
      - cargo publish
      - cmd: cd ../wrapper && cargo publish
      - cmd: cd ../thunkmetrc && cargo publish

  publish:java:
    desc: Publish Java SDK to Maven Central
    dir: sdks/thunkmetrc-java/client
    cmds:
      - mvn clean deploy -P ossrh -Dgpg.passphrase="${GPG_PASSPHRASE}"
      - cmd: cd ../wrapper && mvn clean deploy -P ossrh -Dgpg.passphrase="${GPG_PASSPHRASE}"
      - cmd: cd ../thunkmetrc && mvn clean deploy -P ossrh -Dgpg.passphrase="${GPG_PASSPHRASE}"

  publish:kotlin:
    desc: Publish Kotlin SDK to Maven Central
    cmds:
      - |
        set -e

        publish_module() {
          module_dir="$1"
          artifact_id="$2"

          version="$(awk -F'[<>]' '/<version>/{print $3; exit}' "$module_dir/pom.xml")"
          if [ -z "$version" ]; then
            echo "Error: Unable to determine version for $artifact_id from $module_dir/pom.xml"
            exit 1
          fi

          central_url="https://repo1.maven.org/maven2/io/github/thunkier/${artifact_id}/${version}/${artifact_id}-${version}.pom"
          if curl -fsSI "$central_url" >/dev/null 2>&1; then
            echo "Skipping ${artifact_id}:${version} (already published)"
            return 0
          fi

          echo "Publishing ${artifact_id}:${version}"
          set +e
          output="$(cd "$module_dir" && mvn clean deploy -P ossrh -Dgpg.passphrase="${GPG_PASSPHRASE}" 2>&1)"
          exit_code=$?
          set -e
          echo "$output"

          if [ $exit_code -ne 0 ]; then
            if echo "$output" | grep -qi "already exists"; then
              echo "Detected duplicate publish for ${artifact_id}:${version}; continuing."
              return 0
            fi
            return $exit_code
          fi
        }

        publish_module "sdks/thunkmetrc-kotlin/client" "thunkmetrc-kotlin-client"
        publish_module "sdks/thunkmetrc-kotlin/wrapper" "thunkmetrc-kotlin-wrapper"
        publish_module "sdks/thunkmetrc-kotlin/thunkmetrc" "thunkmetrc-kotlin"
