package models

type FacilityFacilityType struct {
    AdvancedSales bool `json:"AdvancedSales,omitempty"`
    CanAccessCatalog bool `json:"CanAccessCatalog,omitempty"`
    CanAdjustSourcePackagesWithPartials bool `json:"CanAdjustSourcePackagesWithPartials,omitempty"`
    CanAssignLocationsToPackages bool `json:"CanAssignLocationsToPackages,omitempty"`
    CanAssignLocationsToPlantBatches bool `json:"CanAssignLocationsToPlantBatches,omitempty"`
    CanClonePlantBatches bool `json:"CanClonePlantBatches,omitempty"`
    CanCreateDerivedPackages bool `json:"CanCreateDerivedPackages,omitempty"`
    CanCreateImmaturePlantPackagesFromPlants bool `json:"CanCreateImmaturePlantPackagesFromPlants,omitempty"`
    CanCreateOpeningBalancePackages bool `json:"CanCreateOpeningBalancePackages,omitempty"`
    CanCreateOpeningBalancePlantBatches bool `json:"CanCreateOpeningBalancePlantBatches,omitempty"`
    CanCreatePartialPackages bool `json:"CanCreatePartialPackages,omitempty"`
    CanCreateProcessValidationPackages bool `json:"CanCreateProcessValidationPackages,omitempty"`
    CanCreateTradeSamplePackages bool `json:"CanCreateTradeSamplePackages,omitempty"`
    CanDecontaminatePackagesWithFailedLabResults bool `json:"CanDecontaminatePackagesWithFailedLabResults,omitempty"`
    CanDeliverSalesToConsumers bool `json:"CanDeliverSalesToConsumers,omitempty"`
    CanDeliverSalesToPatients bool `json:"CanDeliverSalesToPatients,omitempty"`
    CanDestroyProduct bool `json:"CanDestroyProduct,omitempty"`
    CanDonatePackages bool `json:"CanDonatePackages,omitempty"`
    CanDownloadProductLabel bool `json:"CanDownloadProductLabel,omitempty"`
    CanGrowPlants bool `json:"CanGrowPlants,omitempty"`
    CanHaveMemberPatients bool `json:"CanHaveMemberPatients,omitempty"`
    CanInfuseProducts bool `json:"CanInfuseProducts,omitempty"`
    CanManageItemBrands bool `json:"CanManageItemBrands,omitempty"`
    CanPackageVegetativePlants bool `json:"CanPackageVegetativePlants,omitempty"`
    CanPackageWaste bool `json:"CanPackageWaste,omitempty"`
    CanReceiveAssociateProductLabel bool `json:"CanReceiveAssociateProductLabel,omitempty"`
    CanRecordProcessingJobs bool `json:"CanRecordProcessingJobs,omitempty"`
    CanRecordProductForDestruction bool `json:"CanRecordProductForDestruction,omitempty"`
    CanRemediatePackagesWithFailedLabResults bool `json:"CanRemediatePackagesWithFailedLabResults,omitempty"`
    CanReportAdulteration bool `json:"CanReportAdulteration,omitempty"`
    CanReportHarvestSchedules bool `json:"CanReportHarvestSchedules,omitempty"`
    CanReportOperationalExceptions bool `json:"CanReportOperationalExceptions,omitempty"`
    CanReportPatientCheckIns bool `json:"CanReportPatientCheckIns,omitempty"`
    CanReportPatientsAdverseResponses bool `json:"CanReportPatientsAdverseResponses,omitempty"`
    CanReportStrainProperties bool `json:"CanReportStrainProperties,omitempty"`
    CanRequestProductDecontamination bool `json:"CanRequestProductDecontamination,omitempty"`
    CanRequestProductRemediation bool `json:"CanRequestProductRemediation,omitempty"`
    CanRequireHarvestSampleLabTestBatches bool `json:"CanRequireHarvestSampleLabTestBatches,omitempty"`
    CanRequirePackageSampleLabTestBatches bool `json:"CanRequirePackageSampleLabTestBatches,omitempty"`
    CanReturnPackageQuantity bool `json:"CanReturnPackageQuantity,omitempty"`
    CanSellToCaregivers bool `json:"CanSellToCaregivers,omitempty"`
    CanSellToConsumers bool `json:"CanSellToConsumers,omitempty"`
    CanSellToExternalPatients bool `json:"CanSellToExternalPatients,omitempty"`
    CanSellToPatients bool `json:"CanSellToPatients,omitempty"`
    CanSpecifyPatientSalesLimitExemption bool `json:"CanSpecifyPatientSalesLimitExemption,omitempty"`
    CanSubmitHarvestsForTesting bool `json:"CanSubmitHarvestsForTesting,omitempty"`
    CanSubmitPackagesForTesting bool `json:"CanSubmitPackagesForTesting,omitempty"`
    CanTagPlantBatches bool `json:"CanTagPlantBatches,omitempty"`
    CanTestPackages bool `json:"CanTestPackages,omitempty"`
    CanTrackMotherPlantsAsGrowthPhase bool `json:"CanTrackMotherPlantsAsGrowthPhase,omitempty"`
    CanTrackVegetativePlants bool `json:"CanTrackVegetativePlants,omitempty"`
    CanTransferFromExternalFacilities bool `json:"CanTransferFromExternalFacilities,omitempty"`
    CanUpdateLocationsOnPackages bool `json:"CanUpdateLocationsOnPackages,omitempty"`
    CanUpdatePlantStrains bool `json:"CanUpdatePlantStrains,omitempty"`
    CanUseComplianceLabel bool `json:"CanUseComplianceLabel,omitempty"`
    CanViewSourcePackages bool `json:"CanViewSourcePackages,omitempty"`
    DeliverySalesToNonResidentConsumer bool `json:"DeliverySalesToNonResidentConsumer,omitempty"`
    EnableExternalIdentifier bool `json:"EnableExternalIdentifier,omitempty"`
    EnableSublocations bool `json:"EnableSublocations,omitempty"`
    IsHemp bool `json:"IsHemp,omitempty"`
    IsMedical bool `json:"IsMedical,omitempty"`
    IsRetail bool `json:"IsRetail,omitempty"`
    IsSalesDeliveryHub bool `json:"IsSalesDeliveryHub,omitempty"`
    PackagesRequirePatientAffiliation bool `json:"PackagesRequirePatientAffiliation,omitempty"`
    PlantBatchesCanContainMotherPlants bool `json:"PlantBatchesCanContainMotherPlants,omitempty"`
    PlantsRequirePatientAffiliation bool `json:"PlantsRequirePatientAffiliation,omitempty"`
    RestrictHarvestPlantRestoreTimeHours int64 `json:"RestrictHarvestPlantRestoreTimeHours,omitempty"`
    RestrictPlantBatchAdjustmentTimeHours *int64 `json:"RestrictPlantBatchAdjustmentTimeHours,omitempty"`
    RestrictWholesalePriceEditDays *int64 `json:"RestrictWholesalePriceEditDays,omitempty"`
    RetailSalesToNonResidentConsumer bool `json:"RetailSalesToNonResidentConsumer,omitempty"`
    RetailerDelivery bool `json:"RetailerDelivery,omitempty"`
    RetailerDeliveryAllowDonations bool `json:"RetailerDeliveryAllowDonations,omitempty"`
    RetailerDeliveryAllowPartialPackages bool `json:"RetailerDeliveryAllowPartialPackages,omitempty"`
    RetailerDeliveryAllowTradeSamples bool `json:"RetailerDeliveryAllowTradeSamples,omitempty"`
    RetailerDeliveryRequirePrice bool `json:"RetailerDeliveryRequirePrice,omitempty"`
    SalesDeliveryAllowAddress bool `json:"SalesDeliveryAllowAddress,omitempty"`
    SalesDeliveryAllowCity bool `json:"SalesDeliveryAllowCity,omitempty"`
    SalesDeliveryAllowCounty bool `json:"SalesDeliveryAllowCounty,omitempty"`
    SalesDeliveryAllowPlannedRoute bool `json:"SalesDeliveryAllowPlannedRoute,omitempty"`
    SalesDeliveryAllowState bool `json:"SalesDeliveryAllowState,omitempty"`
    SalesDeliveryAllowZip bool `json:"SalesDeliveryAllowZip,omitempty"`
    SalesDeliveryRequireConsumerId bool `json:"SalesDeliveryRequireConsumerId,omitempty"`
    SalesDeliveryRequirePatientNumber bool `json:"SalesDeliveryRequirePatientNumber,omitempty"`
    SalesDeliveryRequireRecipientName bool `json:"SalesDeliveryRequireRecipientName,omitempty"`
    SalesDeliveryRequireZone bool `json:"SalesDeliveryRequireZone,omitempty"`
    SalesRequireCaregiverNumber bool `json:"SalesRequireCaregiverNumber,omitempty"`
    SalesRequireCaregiverPatientNumber bool `json:"SalesRequireCaregiverPatientNumber,omitempty"`
    SalesRequireExternalPatientIdentificationMethod bool `json:"SalesRequireExternalPatientIdentificationMethod,omitempty"`
    SalesRequireExternalPatientNumber bool `json:"SalesRequireExternalPatientNumber,omitempty"`
    SalesRequirePatientNumber bool `json:"SalesRequirePatientNumber,omitempty"`
    TaxExemptReportingFeesFacilityType bool `json:"TaxExemptReportingFeesFacilityType,omitempty"`
    TaxExemptTagOrdersFacilityType bool `json:"TaxExemptTagOrdersFacilityType,omitempty"`
    TestsRequireLabSample bool `json:"TestsRequireLabSample,omitempty"`
    TotalMemberPatientsAllowed *int64 `json:"TotalMemberPatientsAllowed,omitempty"`
}
