package models

type ItemsUpdateItemsRequestItem struct {
    AdministrationMethod string `json:"AdministrationMethod,omitempty"`
    Allergens string `json:"Allergens,omitempty"`
    Description string `json:"Description,omitempty"`
    GlobalProductName string `json:"GlobalProductName,omitempty"`
    Id int `json:"Id,omitempty"`
    ItemBrand string `json:"ItemBrand,omitempty"`
    ItemCategory string `json:"ItemCategory,omitempty"`
    ItemIngredients string `json:"ItemIngredients,omitempty"`
    LabelImageFileSystemIds string `json:"LabelImageFileSystemIds,omitempty"`
    LabelPhotoDescription string `json:"LabelPhotoDescription,omitempty"`
    Name string `json:"Name,omitempty"`
    NumberOfDoses string `json:"NumberOfDoses,omitempty"`
    PackagingImageFileSystemIds string `json:"PackagingImageFileSystemIds,omitempty"`
    PackagingPhotoDescription string `json:"PackagingPhotoDescription,omitempty"`
    ProcessingJobCategoryName string `json:"ProcessingJobCategoryName,omitempty"`
    ProcessingJobTypeName string `json:"ProcessingJobTypeName,omitempty"`
    ProductImageFileSystemIds string `json:"ProductImageFileSystemIds,omitempty"`
    ProductPDFFileSystemIds string `json:"ProductPDFFileSystemIds,omitempty"`
    ProductPhotoDescription string `json:"ProductPhotoDescription,omitempty"`
    PublicIngredients string `json:"PublicIngredients,omitempty"`
    ServingSize string `json:"ServingSize,omitempty"`
    Strain string `json:"Strain,omitempty"`
    SupplyDurationDays int `json:"SupplyDurationDays,omitempty"`
    UnitCbdAContent float64 `json:"UnitCbdAContent,omitempty"`
    UnitCbdAContentDose float64 `json:"UnitCbdAContentDose,omitempty"`
    UnitCbdAContentDoseUnitOfMeasure string `json:"UnitCbdAContentDoseUnitOfMeasure,omitempty"`
    UnitCbdAContentUnitOfMeasure string `json:"UnitCbdAContentUnitOfMeasure,omitempty"`
    UnitCbdAPercent float64 `json:"UnitCbdAPercent,omitempty"`
    UnitCbdContent float64 `json:"UnitCbdContent,omitempty"`
    UnitCbdContentDose float64 `json:"UnitCbdContentDose,omitempty"`
    UnitCbdContentDoseUnitOfMeasure string `json:"UnitCbdContentDoseUnitOfMeasure,omitempty"`
    UnitCbdContentUnitOfMeasure string `json:"UnitCbdContentUnitOfMeasure,omitempty"`
    UnitCbdPercent float64 `json:"UnitCbdPercent,omitempty"`
    UnitOfMeasure string `json:"UnitOfMeasure,omitempty"`
    UnitThcAContent float64 `json:"UnitThcAContent,omitempty"`
    UnitThcAContentDose float64 `json:"UnitThcAContentDose,omitempty"`
    UnitThcAContentDoseUnitOfMeasure string `json:"UnitThcAContentDoseUnitOfMeasure,omitempty"`
    UnitThcAContentUnitOfMeasure string `json:"UnitThcAContentUnitOfMeasure,omitempty"`
    UnitThcAPercent float64 `json:"UnitThcAPercent,omitempty"`
    UnitThcContent float64 `json:"UnitThcContent,omitempty"`
    UnitThcContentDose float64 `json:"UnitThcContentDose,omitempty"`
    UnitThcContentDoseUnitOfMeasure string `json:"UnitThcContentDoseUnitOfMeasure,omitempty"`
    UnitThcContentUnitOfMeasure string `json:"UnitThcContentUnitOfMeasure,omitempty"`
    UnitThcPercent float64 `json:"UnitThcPercent,omitempty"`
    UnitVolume float64 `json:"UnitVolume,omitempty"`
    UnitVolumeUnitOfMeasure string `json:"UnitVolumeUnitOfMeasure,omitempty"`
    UnitWeight float64 `json:"UnitWeight,omitempty"`
    UnitWeightUnitOfMeasure string `json:"UnitWeightUnitOfMeasure,omitempty"`
}
