package models

type PackagesPackagesPackageItem struct {
    AdministrationMethod *string `json:"AdministrationMethod,omitempty"`
    Allergens *string `json:"Allergens,omitempty"`
    ApprovalStatus int64 `json:"ApprovalStatus,omitempty"`
    ApprovalStatusDateTime string `json:"ApprovalStatusDateTime,omitempty"`
    DefaultLabTestingState int64 `json:"DefaultLabTestingState,omitempty"`
    Description *string `json:"Description,omitempty"`
    GlobalProductName *string `json:"GlobalProductName,omitempty"`
    GlobalProductNumber *string `json:"GlobalProductNumber,omitempty"`
    HasExpirationDate bool `json:"HasExpirationDate,omitempty"`
    HasSellByDate bool `json:"HasSellByDate,omitempty"`
    HasUseByDate bool `json:"HasUseByDate,omitempty"`
    Id int64 `json:"Id,omitempty"`
    IsExpirationDateRequired bool `json:"IsExpirationDateRequired,omitempty"`
    IsSellByDateRequired bool `json:"IsSellByDateRequired,omitempty"`
    IsUseByDateRequired bool `json:"IsUseByDateRequired,omitempty"`
    IsUsed bool `json:"IsUsed,omitempty"`
    ItemBrandId int64 `json:"ItemBrandId,omitempty"`
    ItemBrandName *string `json:"ItemBrandName,omitempty"`
    LabTestBatchNames []interface{} `json:"LabTestBatchNames,omitempty"`
    LabelImages []interface{} `json:"LabelImages,omitempty"`
    LabelPhotoDescription *string `json:"LabelPhotoDescription,omitempty"`
    Name string `json:"Name,omitempty"`
    NumberOfDoses *string `json:"NumberOfDoses,omitempty"`
    PackagingImages []interface{} `json:"PackagingImages,omitempty"`
    PackagingPhotoDescription *string `json:"PackagingPhotoDescription,omitempty"`
    ProcessingJobCategoryName *string `json:"ProcessingJobCategoryName,omitempty"`
    ProcessingJobTypeName *string `json:"ProcessingJobTypeName,omitempty"`
    ProductBrandName *string `json:"ProductBrandName,omitempty"`
    ProductCategoryName string `json:"ProductCategoryName,omitempty"`
    ProductCategoryType int64 `json:"ProductCategoryType,omitempty"`
    ProductImages []interface{} `json:"ProductImages,omitempty"`
    ProductPDFDocuments []interface{} `json:"ProductPDFDocuments,omitempty"`
    ProductPhotoDescription *string `json:"ProductPhotoDescription,omitempty"`
    PublicIngredients *string `json:"PublicIngredients,omitempty"`
    QuantityType int64 `json:"QuantityType,omitempty"`
    ServingSize *string `json:"ServingSize,omitempty"`
    StrainId *int64 `json:"StrainId,omitempty"`
    StrainName *string `json:"StrainName,omitempty"`
    UnitCbdAContent *float64 `json:"UnitCbdAContent,omitempty"`
    UnitCbdAContentDose *float64 `json:"UnitCbdAContentDose,omitempty"`
    UnitCbdAContentDoseUnitOfMeasureName *string `json:"UnitCbdAContentDoseUnitOfMeasureName,omitempty"`
    UnitCbdAContentUnitOfMeasureName *string `json:"UnitCbdAContentUnitOfMeasureName,omitempty"`
    UnitCbdAPercent *float64 `json:"UnitCbdAPercent,omitempty"`
    UnitCbdContent *float64 `json:"UnitCbdContent,omitempty"`
    UnitCbdContentDose *float64 `json:"UnitCbdContentDose,omitempty"`
    UnitCbdContentDoseUnitOfMeasureName *string `json:"UnitCbdContentDoseUnitOfMeasureName,omitempty"`
    UnitCbdContentUnitOfMeasureName *string `json:"UnitCbdContentUnitOfMeasureName,omitempty"`
    UnitCbdPercent *float64 `json:"UnitCbdPercent,omitempty"`
    UnitOfMeasureName *string `json:"UnitOfMeasureName,omitempty"`
    UnitQuantity *float64 `json:"UnitQuantity,omitempty"`
    UnitQuantityUnitOfMeasureName *string `json:"UnitQuantityUnitOfMeasureName,omitempty"`
    UnitThcAContent *float64 `json:"UnitThcAContent,omitempty"`
    UnitThcAContentDose *float64 `json:"UnitThcAContentDose,omitempty"`
    UnitThcAContentDoseUnitOfMeasureId *int64 `json:"UnitThcAContentDoseUnitOfMeasureId,omitempty"`
    UnitThcAContentDoseUnitOfMeasureName *string `json:"UnitThcAContentDoseUnitOfMeasureName,omitempty"`
    UnitThcAContentUnitOfMeasureName *string `json:"UnitThcAContentUnitOfMeasureName,omitempty"`
    UnitThcAPercent *float64 `json:"UnitThcAPercent,omitempty"`
    UnitThcContent *float64 `json:"UnitThcContent,omitempty"`
    UnitThcContentDose *float64 `json:"UnitThcContentDose,omitempty"`
    UnitThcContentDoseUnitOfMeasureId *int64 `json:"UnitThcContentDoseUnitOfMeasureId,omitempty"`
    UnitThcContentDoseUnitOfMeasureName *string `json:"UnitThcContentDoseUnitOfMeasureName,omitempty"`
    UnitThcContentUnitOfMeasureName *string `json:"UnitThcContentUnitOfMeasureName,omitempty"`
    UnitThcPercent *float64 `json:"UnitThcPercent,omitempty"`
    UnitVolume *float64 `json:"UnitVolume,omitempty"`
    UnitVolumeUnitOfMeasureName *string `json:"UnitVolumeUnitOfMeasureName,omitempty"`
    UnitWeight *float64 `json:"UnitWeight,omitempty"`
    UnitWeightUnitOfMeasureName *string `json:"UnitWeightUnitOfMeasureName,omitempty"`
}
