package models

type SalesSaleDeliveryRetailerDestinationsItem struct {
    AcceptedDateTime *string `json:"AcceptedDateTime,omitempty"`
    ActualArrivalDateTime *string `json:"ActualArrivalDateTime,omitempty"`
    ActualDepartureDateTime *string `json:"ActualDepartureDateTime,omitempty"`
    ActualReturnArrivalDateTime *string `json:"ActualReturnArrivalDateTime,omitempty"`
    ActualReturnDepartureDateTime *string `json:"ActualReturnDepartureDateTime,omitempty"`
    CompletedDateTime *string `json:"CompletedDateTime,omitempty"`
    ConsumerId string `json:"ConsumerId,omitempty"`
    DeliveryNumber *string `json:"DeliveryNumber,omitempty"`
    Direction string `json:"Direction,omitempty"`
    DriverEmployeeId string `json:"DriverEmployeeId,omitempty"`
    DriverName string `json:"DriverName,omitempty"`
    DriversLicenseNumber string `json:"DriversLicenseNumber,omitempty"`
    EstimatedArrivalDateTime string `json:"EstimatedArrivalDateTime,omitempty"`
    EstimatedDepartureDateTime string `json:"EstimatedDepartureDateTime,omitempty"`
    EstimatedReturnArrivalDateTime *string `json:"EstimatedReturnArrivalDateTime,omitempty"`
    EstimatedReturnDepartureDateTime *string `json:"EstimatedReturnDepartureDateTime,omitempty"`
    FacilityLicenseNumber *string `json:"FacilityLicenseNumber,omitempty"`
    FacilityName *string `json:"FacilityName,omitempty"`
    Id int64 `json:"Id,omitempty"`
    LastModified string `json:"LastModified,omitempty"`
    PatientLicenseNumber *string `json:"PatientLicenseNumber,omitempty"`
    PlannedRoute string `json:"PlannedRoute,omitempty"`
    RecipientAddressCity string `json:"RecipientAddressCity,omitempty"`
    RecipientAddressCounty *string `json:"RecipientAddressCounty,omitempty"`
    RecipientAddressPostalCode string `json:"RecipientAddressPostalCode,omitempty"`
    RecipientAddressState string `json:"RecipientAddressState,omitempty"`
    RecipientAddressStreet1 string `json:"RecipientAddressStreet1,omitempty"`
    RecipientAddressStreet2 string `json:"RecipientAddressStreet2,omitempty"`
    RecipientDeliveryZoneId *int64 `json:"RecipientDeliveryZoneId,omitempty"`
    RecipientDeliveryZoneName *string `json:"RecipientDeliveryZoneName,omitempty"`
    RecipientName *string `json:"RecipientName,omitempty"`
    RecipientZoneId *int64 `json:"RecipientZoneId,omitempty"`
    RecordedByUserName *string `json:"RecordedByUserName,omitempty"`
    RecordedDateTime string `json:"RecordedDateTime,omitempty"`
    SalesCustomerType string `json:"SalesCustomerType,omitempty"`
    SalesDateTime string `json:"SalesDateTime,omitempty"`
    SalesDeliveryState string `json:"SalesDeliveryState,omitempty"`
    ShipperFacilityLicenseNumber *string `json:"ShipperFacilityLicenseNumber,omitempty"`
    TotalPackages int64 `json:"TotalPackages,omitempty"`
    TotalPrice int64 `json:"TotalPrice,omitempty"`
    Transactions []interface{} `json:"Transactions,omitempty"`
    TransporterFacilityId *int64 `json:"TransporterFacilityId,omitempty"`
    TransporterFacilityLicenseNumber *string `json:"TransporterFacilityLicenseNumber,omitempty"`
    TransporterFacilityName *string `json:"TransporterFacilityName,omitempty"`
    VehicleLicensePlateNumber string `json:"VehicleLicensePlateNumber,omitempty"`
    VehicleMake string `json:"VehicleMake,omitempty"`
    VehicleModel string `json:"VehicleModel,omitempty"`
    VoidedDate *string `json:"VoidedDate,omitempty"`
}
