package models

type TransferDeliveryPackage struct {
    ContainsRemediatedProduct bool `json:"ContainsRemediatedProduct,omitempty"`
    ExpirationDate *string `json:"ExpirationDate,omitempty"`
    ExternalId *int64 `json:"ExternalId,omitempty"`
    GrossUnitOfWeightName *string `json:"GrossUnitOfWeightName,omitempty"`
    IsDonation bool `json:"IsDonation,omitempty"`
    IsTestingSample bool `json:"IsTestingSample,omitempty"`
    IsTradeSample bool `json:"IsTradeSample,omitempty"`
    IsTradeSamplePersistent bool `json:"IsTradeSamplePersistent,omitempty"`
    ItemBrandName *string `json:"ItemBrandName,omitempty"`
    ItemCategoryName string `json:"ItemCategoryName,omitempty"`
    ItemId int64 `json:"ItemId,omitempty"`
    ItemName string `json:"ItemName,omitempty"`
    ItemServingSize *string `json:"ItemServingSize,omitempty"`
    ItemStrainName *string `json:"ItemStrainName,omitempty"`
    ItemSupplyDurationDays *int64 `json:"ItemSupplyDurationDays,omitempty"`
    ItemUnitCbdAContent *float64 `json:"ItemUnitCbdAContent,omitempty"`
    ItemUnitCbdAContentDose *float64 `json:"ItemUnitCbdAContentDose,omitempty"`
    ItemUnitCbdAContentDoseUnitOfMeasureName *string `json:"ItemUnitCbdAContentDoseUnitOfMeasureName,omitempty"`
    ItemUnitCbdAContentUnitOfMeasureName *string `json:"ItemUnitCbdAContentUnitOfMeasureName,omitempty"`
    ItemUnitCbdAPercent *float64 `json:"ItemUnitCbdAPercent,omitempty"`
    ItemUnitCbdContent *float64 `json:"ItemUnitCbdContent,omitempty"`
    ItemUnitCbdContentDose *float64 `json:"ItemUnitCbdContentDose,omitempty"`
    ItemUnitCbdContentDoseUnitOfMeasureName *string `json:"ItemUnitCbdContentDoseUnitOfMeasureName,omitempty"`
    ItemUnitCbdContentUnitOfMeasureName *string `json:"ItemUnitCbdContentUnitOfMeasureName,omitempty"`
    ItemUnitCbdPercent *float64 `json:"ItemUnitCbdPercent,omitempty"`
    ItemUnitQuantity *float64 `json:"ItemUnitQuantity,omitempty"`
    ItemUnitQuantityUnitOfMeasureName *string `json:"ItemUnitQuantityUnitOfMeasureName,omitempty"`
    ItemUnitThcAContent *float64 `json:"ItemUnitThcAContent,omitempty"`
    ItemUnitThcAContentDose *float64 `json:"ItemUnitThcAContentDose,omitempty"`
    ItemUnitThcAContentDoseUnitOfMeasureName *string `json:"ItemUnitThcAContentDoseUnitOfMeasureName,omitempty"`
    ItemUnitThcAContentUnitOfMeasureName *string `json:"ItemUnitThcAContentUnitOfMeasureName,omitempty"`
    ItemUnitThcAPercent *float64 `json:"ItemUnitThcAPercent,omitempty"`
    ItemUnitThcContent *float64 `json:"ItemUnitThcContent,omitempty"`
    ItemUnitThcContentDose *float64 `json:"ItemUnitThcContentDose,omitempty"`
    ItemUnitThcContentDoseUnitOfMeasureName *string `json:"ItemUnitThcContentDoseUnitOfMeasureName,omitempty"`
    ItemUnitThcContentUnitOfMeasureName *string `json:"ItemUnitThcContentUnitOfMeasureName,omitempty"`
    ItemUnitThcPercent *float64 `json:"ItemUnitThcPercent,omitempty"`
    ItemUnitVolume *float64 `json:"ItemUnitVolume,omitempty"`
    ItemUnitVolumeUnitOfMeasureName *string `json:"ItemUnitVolumeUnitOfMeasureName,omitempty"`
    ItemUnitWeight *float64 `json:"ItemUnitWeight,omitempty"`
    ItemUnitWeightUnitOfMeasureName *string `json:"ItemUnitWeightUnitOfMeasureName,omitempty"`
    LabTestingState string `json:"LabTestingState,omitempty"`
    PackageId int64 `json:"PackageId,omitempty"`
    PackageLabel string `json:"PackageLabel,omitempty"`
    PackageType string `json:"PackageType,omitempty"`
    PackagedDate *string `json:"PackagedDate,omitempty"`
    ProductLabel TransfersTransferDeliveryPackageProductLabel `json:"ProductLabel,omitempty"`
    ProductRequiresRemediation bool `json:"ProductRequiresRemediation,omitempty"`
    ProductionBatchNumber *string `json:"ProductionBatchNumber,omitempty"`
    ReceivedQuantity float64 `json:"ReceivedQuantity,omitempty"`
    ReceivedUnitOfMeasureName string `json:"ReceivedUnitOfMeasureName,omitempty"`
    RemediationDate *string `json:"RemediationDate,omitempty"`
    SellByDate *string `json:"SellByDate,omitempty"`
    ShipmentPackageState string `json:"ShipmentPackageState,omitempty"`
    ShippedQuantity float64 `json:"ShippedQuantity,omitempty"`
    ShippedUnitOfMeasureName string `json:"ShippedUnitOfMeasureName,omitempty"`
    SourceHarvestNames *string `json:"SourceHarvestNames,omitempty"`
    SourcePackageIsDonation bool `json:"SourcePackageIsDonation,omitempty"`
    SourcePackageIsTradeSample bool `json:"SourcePackageIsTradeSample,omitempty"`
    SourcePackageLabels *string `json:"SourcePackageLabels,omitempty"`
    SourceProductionBatchNumbers *string `json:"SourceProductionBatchNumbers,omitempty"`
    UseByDate *string `json:"UseByDate,omitempty"`
}
