package models

type WastePackage struct {
    ArchivedDate *string `json:"ArchivedDate,omitempty"`
    ContainsDecontaminatedProduct bool `json:"ContainsDecontaminatedProduct,omitempty"`
    ContainsRemediatedProduct bool `json:"ContainsRemediatedProduct,omitempty"`
    DecontaminationDate *string `json:"DecontaminationDate,omitempty"`
    ExpirationDate *string `json:"ExpirationDate,omitempty"`
    ExternalId *int64 `json:"ExternalId,omitempty"`
    FinishedDate *string `json:"FinishedDate,omitempty"`
    Id int64 `json:"Id,omitempty"`
    InitialLabTestingState string `json:"InitialLabTestingState,omitempty"`
    IsDonation bool `json:"IsDonation,omitempty"`
    IsDonationPersistent bool `json:"IsDonationPersistent,omitempty"`
    IsFinished bool `json:"IsFinished,omitempty"`
    IsFinishedGood bool `json:"IsFinishedGood,omitempty"`
    IsOnHold bool `json:"IsOnHold,omitempty"`
    IsOnHoldCombined bool `json:"IsOnHoldCombined,omitempty"`
    IsOnInvestigation bool `json:"IsOnInvestigation,omitempty"`
    IsOnInvestigationHold bool `json:"IsOnInvestigationHold,omitempty"`
    IsOnInvestigationRecall bool `json:"IsOnInvestigationRecall,omitempty"`
    IsOnRecall *bool `json:"IsOnRecall,omitempty"`
    IsOnRecallCombined bool `json:"IsOnRecallCombined,omitempty"`
    IsOnRetailerDelivery bool `json:"IsOnRetailerDelivery,omitempty"`
    IsProcessValidationTestingSample bool `json:"IsProcessValidationTestingSample,omitempty"`
    IsProductionBatch bool `json:"IsProductionBatch,omitempty"`
    IsTestingSample bool `json:"IsTestingSample,omitempty"`
    IsTradeSample bool `json:"IsTradeSample,omitempty"`
    IsTradeSamplePersistent bool `json:"IsTradeSamplePersistent,omitempty"`
    Item PlantsWastePackageItem `json:"Item,omitempty"`
    ItemFromFacilityLicenseNumber *string `json:"ItemFromFacilityLicenseNumber,omitempty"`
    ItemFromFacilityName *string `json:"ItemFromFacilityName,omitempty"`
    LabTestResultExpirationDateTime *string `json:"LabTestResultExpirationDateTime,omitempty"`
    LabTestStage *string `json:"LabTestStage,omitempty"`
    LabTestStageId *int64 `json:"LabTestStageId,omitempty"`
    LabTestingPerformedDate *string `json:"LabTestingPerformedDate,omitempty"`
    LabTestingRecordedDate *string `json:"LabTestingRecordedDate,omitempty"`
    LabTestingState string `json:"LabTestingState,omitempty"`
    LabTestingStateDate string `json:"LabTestingStateDate,omitempty"`
    Label string `json:"Label,omitempty"`
    LabelsLastGeneratedDateTime *string `json:"LabelsLastGeneratedDateTime,omitempty"`
    LastModified string `json:"LastModified,omitempty"`
    LocationId *int64 `json:"LocationId,omitempty"`
    LocationName *string `json:"LocationName,omitempty"`
    LocationTypeName *string `json:"LocationTypeName,omitempty"`
    Note *string `json:"Note,omitempty"`
    OriginalPackageQuantity float64 `json:"OriginalPackageQuantity,omitempty"`
    PackageForProductDestruction *string `json:"PackageForProductDestruction,omitempty"`
    PackageType string `json:"PackageType,omitempty"`
    PackagedDate string `json:"PackagedDate,omitempty"`
    PatientLicenseNumber *string `json:"PatientLicenseNumber,omitempty"`
    ProductLabel PlantsWastePackageProductLabel `json:"ProductLabel,omitempty"`
    ProductRequiresDecontamination bool `json:"ProductRequiresDecontamination,omitempty"`
    ProductRequiresRemediation bool `json:"ProductRequiresRemediation,omitempty"`
    ProductionBatchNumber *string `json:"ProductionBatchNumber,omitempty"`
    Quantity float64 `json:"Quantity,omitempty"`
    ReceivedDateTime *string `json:"ReceivedDateTime,omitempty"`
    ReceivedFromFacilityLicenseNumber *string `json:"ReceivedFromFacilityLicenseNumber,omitempty"`
    ReceivedFromFacilityName *string `json:"ReceivedFromFacilityName,omitempty"`
    ReceivedFromManifestNumber *string `json:"ReceivedFromManifestNumber,omitempty"`
    RemediationDate *string `json:"RemediationDate,omitempty"`
    SellByDate *string `json:"SellByDate,omitempty"`
    SourceHarvestCount int64 `json:"SourceHarvestCount,omitempty"`
    SourceHarvestNames *string `json:"SourceHarvestNames,omitempty"`
    SourcePackageCount int64 `json:"SourcePackageCount,omitempty"`
    SourcePackageIsDonation bool `json:"SourcePackageIsDonation,omitempty"`
    SourcePackageIsTradeSample bool `json:"SourcePackageIsTradeSample,omitempty"`
    SourcePackageLabels *string `json:"SourcePackageLabels,omitempty"`
    SourceProcessingJobCount int64 `json:"SourceProcessingJobCount,omitempty"`
    SourceProductionBatchNumbers *string `json:"SourceProductionBatchNumbers,omitempty"`
    SublocationId *int64 `json:"SublocationId,omitempty"`
    SublocationName *string `json:"SublocationName,omitempty"`
    UnitOfMeasureAbbreviation string `json:"UnitOfMeasureAbbreviation,omitempty"`
    UnitOfMeasureName string `json:"UnitOfMeasureName,omitempty"`
    UseByDate *string `json:"UseByDate,omitempty"`
}
