export * from '@thunkier/thunkmetrc-client';
import { MetrcClient as InternalMetrcClient } from '@thunkier/thunkmetrc-client';
import { MetrcRateLimiter, RateLimiterConfig } from './RateLimiter';

export * from './models';
export * from './services/AdditivesTemplatesService';
import { AdditivesTemplatesService } from './services/AdditivesTemplatesService';
export * from './services/CaregiversStatusService';
import { CaregiversStatusService } from './services/CaregiversStatusService';
export * from './services/EmployeesService';
import { EmployeesService } from './services/EmployeesService';
export * from './services/FacilitiesService';
import { FacilitiesService } from './services/FacilitiesService';
export * from './services/HarvestsService';
import { HarvestsService } from './services/HarvestsService';
export * from './services/ItemsService';
import { ItemsService } from './services/ItemsService';
export * from './services/LabTestsService';
import { LabTestsService } from './services/LabTestsService';
export * from './services/LocationsService';
import { LocationsService } from './services/LocationsService';
export * from './services/PackagesService';
import { PackagesService } from './services/PackagesService';
export * from './services/PatientCheckInsService';
import { PatientCheckInsService } from './services/PatientCheckInsService';
export * from './services/PatientsService';
import { PatientsService } from './services/PatientsService';
export * from './services/PatientsStatusService';
import { PatientsStatusService } from './services/PatientsStatusService';
export * from './services/PlantBatchesService';
import { PlantBatchesService } from './services/PlantBatchesService';
export * from './services/PlantsService';
import { PlantsService } from './services/PlantsService';
export * from './services/ProcessingJobService';
import { ProcessingJobService } from './services/ProcessingJobService';
export * from './services/RetailIdService';
import { RetailIdService } from './services/RetailIdService';
export * from './services/SalesService';
import { SalesService } from './services/SalesService';
export * from './services/SandboxService';
import { SandboxService } from './services/SandboxService';
export * from './services/StrainsService';
import { StrainsService } from './services/StrainsService';
export * from './services/SublocationsService';
import { SublocationsService } from './services/SublocationsService';
export * from './services/TagsService';
import { TagsService } from './services/TagsService';
export * from './services/TransfersService';
import { TransfersService } from './services/TransfersService';
export * from './services/TransportersService';
import { TransportersService } from './services/TransportersService';
export * from './services/UnitsOfMeasureService';
import { UnitsOfMeasureService } from './services/UnitsOfMeasureService';
export * from './services/WasteMethodsService';
import { WasteMethodsService } from './services/WasteMethodsService';
export * from './services/WebhooksService';
import { WebhooksService } from './services/WebhooksService';

export class MetrcWrapper {
  private rateLimiter: MetrcRateLimiter;
  public additivesTemplates: AdditivesTemplatesService;
  public caregiversStatus: CaregiversStatusService;
  public employees: EmployeesService;
  public facilities: FacilitiesService;
  public harvests: HarvestsService;
  public items: ItemsService;
  public labTests: LabTestsService;
  public locations: LocationsService;
  public packages: PackagesService;
  public patientCheckIns: PatientCheckInsService;
  public patients: PatientsService;
  public patientsStatus: PatientsStatusService;
  public plantBatches: PlantBatchesService;
  public plants: PlantsService;
  public processingJob: ProcessingJobService;
  public retailId: RetailIdService;
  public sales: SalesService;
  public sandbox: SandboxService;
  public strains: StrainsService;
  public sublocations: SublocationsService;
  public tags: TagsService;
  public transfers: TransfersService;
  public transporters: TransportersService;
  public unitsOfMeasure: UnitsOfMeasureService;
  public wasteMethods: WasteMethodsService;
  public webhooks: WebhooksService;

  constructor(public client: InternalMetrcClient, configOrLimiter?: RateLimiterConfig | MetrcRateLimiter) {
    if (configOrLimiter instanceof MetrcRateLimiter) {
      this.rateLimiter = configOrLimiter;
    } else {
      this.rateLimiter = new MetrcRateLimiter(configOrLimiter);
    }
    this.additivesTemplates = new AdditivesTemplatesService(client, this.rateLimiter);
    this.caregiversStatus = new CaregiversStatusService(client, this.rateLimiter);
    this.employees = new EmployeesService(client, this.rateLimiter);
    this.facilities = new FacilitiesService(client, this.rateLimiter);
    this.harvests = new HarvestsService(client, this.rateLimiter);
    this.items = new ItemsService(client, this.rateLimiter);
    this.labTests = new LabTestsService(client, this.rateLimiter);
    this.locations = new LocationsService(client, this.rateLimiter);
    this.packages = new PackagesService(client, this.rateLimiter);
    this.patientCheckIns = new PatientCheckInsService(client, this.rateLimiter);
    this.patients = new PatientsService(client, this.rateLimiter);
    this.patientsStatus = new PatientsStatusService(client, this.rateLimiter);
    this.plantBatches = new PlantBatchesService(client, this.rateLimiter);
    this.plants = new PlantsService(client, this.rateLimiter);
    this.processingJob = new ProcessingJobService(client, this.rateLimiter);
    this.retailId = new RetailIdService(client, this.rateLimiter);
    this.sales = new SalesService(client, this.rateLimiter);
    this.sandbox = new SandboxService(client, this.rateLimiter);
    this.strains = new StrainsService(client, this.rateLimiter);
    this.sublocations = new SublocationsService(client, this.rateLimiter);
    this.tags = new TagsService(client, this.rateLimiter);
    this.transfers = new TransfersService(client, this.rateLimiter);
    this.transporters = new TransportersService(client, this.rateLimiter);
    this.unitsOfMeasure = new UnitsOfMeasureService(client, this.rateLimiter);
    this.wasteMethods = new WasteMethodsService(client, this.rateLimiter);
    this.webhooks = new WebhooksService(client, this.rateLimiter);
  }
}
