package models

type Item struct {
	Ids []float64 `json:"Ids"`
	Warnings *string `json:"Warnings"`
	AdministrationMethod *string `json:"AdministrationMethod"`
	Allergens *string `json:"Allergens"`
	ApprovalStatus string `json:"ApprovalStatus"`
	ApprovalStatusDateTime string `json:"ApprovalStatusDateTime"`
	DefaultLabTestingState string `json:"DefaultLabTestingState"`
	Description *string `json:"Description"`
	GlobalProductName *string `json:"GlobalProductName"`
	GlobalProductNumber *string `json:"GlobalProductNumber"`
	HasExpirationDate bool `json:"HasExpirationDate"`
	HasSellByDate bool `json:"HasSellByDate"`
	HasUseByDate bool `json:"HasUseByDate"`
	Id int `json:"Id"`
	IsExpirationDateRequired bool `json:"IsExpirationDateRequired"`
	IsSellByDateRequired bool `json:"IsSellByDateRequired"`
	IsUseByDateRequired bool `json:"IsUseByDateRequired"`
	IsUsed bool `json:"IsUsed"`
	ItemBrandId int `json:"ItemBrandId"`
	ItemBrandName *string `json:"ItemBrandName"`
	LabTestBatchNames []interface{} `json:"LabTestBatchNames"`
	LabelImages []interface{} `json:"LabelImages"`
	LabelPhotoDescription *string `json:"LabelPhotoDescription"`
	Name string `json:"Name"`
	NumberOfDoses *string `json:"NumberOfDoses"`
	PackagingImages []interface{} `json:"PackagingImages"`
	PackagingPhotoDescription *string `json:"PackagingPhotoDescription"`
	ProcessingJobCategoryName *string `json:"ProcessingJobCategoryName"`
	ProcessingJobTypeName *string `json:"ProcessingJobTypeName"`
	ProductBrandName *string `json:"ProductBrandName"`
	ProductCategoryName string `json:"ProductCategoryName"`
	ProductCategoryType string `json:"ProductCategoryType"`
	ProductImages []interface{} `json:"ProductImages"`
	ProductPDFDocuments []interface{} `json:"ProductPDFDocuments"`
	ProductPhotoDescription *string `json:"ProductPhotoDescription"`
	PublicIngredients *string `json:"PublicIngredients"`
	QuantityType string `json:"QuantityType"`
	ServingSize *string `json:"ServingSize"`
	StrainId int `json:"StrainId"`
	StrainName string `json:"StrainName"`
	UnitCbdAContent *float64 `json:"UnitCbdAContent"`
	UnitCbdAContentDose *float64 `json:"UnitCbdAContentDose"`
	UnitCbdAContentDoseUnitOfMeasureName *string `json:"UnitCbdAContentDoseUnitOfMeasureName"`
	UnitCbdAContentUnitOfMeasureName *string `json:"UnitCbdAContentUnitOfMeasureName"`
	UnitCbdAPercent *float64 `json:"UnitCbdAPercent"`
	UnitCbdContent *float64 `json:"UnitCbdContent"`
	UnitCbdContentDose *float64 `json:"UnitCbdContentDose"`
	UnitCbdContentDoseUnitOfMeasureName *string `json:"UnitCbdContentDoseUnitOfMeasureName"`
	UnitCbdContentUnitOfMeasureName *string `json:"UnitCbdContentUnitOfMeasureName"`
	UnitCbdPercent *float64 `json:"UnitCbdPercent"`
	UnitOfMeasureName string `json:"UnitOfMeasureName"`
	UnitQuantity *string `json:"UnitQuantity"`
	UnitQuantityUnitOfMeasureName *string `json:"UnitQuantityUnitOfMeasureName"`
	UnitThcAContent *float64 `json:"UnitThcAContent"`
	UnitThcAContentDose *float64 `json:"UnitThcAContentDose"`
	UnitThcAContentDoseUnitOfMeasureId *int `json:"UnitThcAContentDoseUnitOfMeasureId"`
	UnitThcAContentDoseUnitOfMeasureName *string `json:"UnitThcAContentDoseUnitOfMeasureName"`
	UnitThcAContentUnitOfMeasureName *string `json:"UnitThcAContentUnitOfMeasureName"`
	UnitThcAPercent *float64 `json:"UnitThcAPercent"`
	UnitThcContent *float64 `json:"UnitThcContent"`
	UnitThcContentDose *float64 `json:"UnitThcContentDose"`
	UnitThcContentDoseUnitOfMeasureId *int `json:"UnitThcContentDoseUnitOfMeasureId"`
	UnitThcContentDoseUnitOfMeasureName *string `json:"UnitThcContentDoseUnitOfMeasureName"`
	UnitThcContentUnitOfMeasureName *string `json:"UnitThcContentUnitOfMeasureName"`
	UnitThcPercent *float64 `json:"UnitThcPercent"`
	UnitVolume *float64 `json:"UnitVolume"`
	UnitVolumeUnitOfMeasureName *string `json:"UnitVolumeUnitOfMeasureName"`
	UnitWeight *float64 `json:"UnitWeight"`
	UnitWeightUnitOfMeasureName *string `json:"UnitWeightUnitOfMeasureName"`
	CurrentPage int `json:"CurrentPage"`
	Data []ItemData `json:"Data"`
	Page int `json:"Page"`
	PageSize int `json:"PageSize"`
	RecordsOnPage int `json:"RecordsOnPage"`
	Total int `json:"Total"`
	TotalPages int `json:"TotalPages"`
	TotalRecords int `json:"TotalRecords"`
	Status string `json:"Status"`
	CanBeDecontaminated bool `json:"CanBeDecontaminated"`
	CanBeDestroyed bool `json:"CanBeDestroyed"`
	CanBeRemediated bool `json:"CanBeRemediated"`
	CanContainSeeds bool `json:"CanContainSeeds"`
	RequiresAdministrationMethod bool `json:"RequiresAdministrationMethod"`
	RequiresAllergens bool `json:"RequiresAllergens"`
	RequiresDescription bool `json:"RequiresDescription"`
	RequiresItemBrand bool `json:"RequiresItemBrand"`
	RequiresLabelPhotoDescription bool `json:"RequiresLabelPhotoDescription"`
	RequiresLabelPhotos int `json:"RequiresLabelPhotos"`
	RequiresNumberOfDoses bool `json:"RequiresNumberOfDoses"`
	RequiresPackagingPhotoDescription bool `json:"RequiresPackagingPhotoDescription"`
	RequiresPackagingPhotos int `json:"RequiresPackagingPhotos"`
	RequiresProductPDFDocuments int `json:"RequiresProductPDFDocuments"`
	RequiresProductPhotoDescription bool `json:"RequiresProductPhotoDescription"`
	RequiresProductPhotos int `json:"RequiresProductPhotos"`
	RequiresPublicIngredients bool `json:"RequiresPublicIngredients"`
	RequiresServingSize bool `json:"RequiresServingSize"`
	RequiresStrain bool `json:"RequiresStrain"`
	RequiresSupplyDurationDays bool `json:"RequiresSupplyDurationDays"`
	RequiresUnitCbdAContent bool `json:"RequiresUnitCbdAContent"`
	RequiresUnitCbdAContentDose bool `json:"RequiresUnitCbdAContentDose"`
	RequiresUnitCbdAPercent bool `json:"RequiresUnitCbdAPercent"`
	RequiresUnitCbdContent bool `json:"RequiresUnitCbdContent"`
	RequiresUnitCbdContentDose bool `json:"RequiresUnitCbdContentDose"`
	RequiresUnitCbdPercent bool `json:"RequiresUnitCbdPercent"`
	RequiresUnitThcAContent bool `json:"RequiresUnitThcAContent"`
	RequiresUnitThcAContentDose bool `json:"RequiresUnitThcAContentDose"`
	RequiresUnitThcAPercent bool `json:"RequiresUnitThcAPercent"`
	RequiresUnitThcContent bool `json:"RequiresUnitThcContent"`
	RequiresUnitThcContentDose bool `json:"RequiresUnitThcContentDose"`
	RequiresUnitThcPercent bool `json:"RequiresUnitThcPercent"`
	RequiresUnitVolume bool `json:"RequiresUnitVolume"`
	RequiresUnitWeight bool `json:"RequiresUnitWeight"`
	ContentType string `json:"ContentType"`
	FileContents string `json:"FileContents"`
	FileDownloadName string `json:"FileDownloadName"`
}

type ItemData struct {
	AdministrationMethod *string `json:"AdministrationMethod"`
	Allergens *string `json:"Allergens"`
	ApprovalStatus string `json:"ApprovalStatus"`
	ApprovalStatusDateTime string `json:"ApprovalStatusDateTime"`
	DefaultLabTestingState string `json:"DefaultLabTestingState"`
	Description *string `json:"Description"`
	GlobalProductName *string `json:"GlobalProductName"`
	GlobalProductNumber *string `json:"GlobalProductNumber"`
	HasExpirationDate bool `json:"HasExpirationDate"`
	HasSellByDate bool `json:"HasSellByDate"`
	HasUseByDate bool `json:"HasUseByDate"`
	Id int `json:"Id"`
	IsExpirationDateRequired bool `json:"IsExpirationDateRequired"`
	IsSellByDateRequired bool `json:"IsSellByDateRequired"`
	IsUseByDateRequired bool `json:"IsUseByDateRequired"`
	IsUsed bool `json:"IsUsed"`
	ItemBrandId int `json:"ItemBrandId"`
	ItemBrandName *string `json:"ItemBrandName"`
	LabTestBatchNames []interface{} `json:"LabTestBatchNames"`
	LabelImages []interface{} `json:"LabelImages"`
	LabelPhotoDescription *string `json:"LabelPhotoDescription"`
	Name string `json:"Name"`
	NumberOfDoses *string `json:"NumberOfDoses"`
	PackagingImages []interface{} `json:"PackagingImages"`
	PackagingPhotoDescription *string `json:"PackagingPhotoDescription"`
	ProcessingJobCategoryName *string `json:"ProcessingJobCategoryName"`
	ProcessingJobTypeName *string `json:"ProcessingJobTypeName"`
	ProductBrandName *string `json:"ProductBrandName"`
	ProductCategoryName string `json:"ProductCategoryName"`
	ProductCategoryType string `json:"ProductCategoryType"`
	ProductImages []interface{} `json:"ProductImages"`
	ProductPDFDocuments []interface{} `json:"ProductPDFDocuments"`
	ProductPhotoDescription *string `json:"ProductPhotoDescription"`
	PublicIngredients *string `json:"PublicIngredients"`
	QuantityType string `json:"QuantityType"`
	ServingSize *string `json:"ServingSize"`
	StrainId int `json:"StrainId"`
	StrainName string `json:"StrainName"`
	UnitCbdAContent *float64 `json:"UnitCbdAContent"`
	UnitCbdAContentDose *float64 `json:"UnitCbdAContentDose"`
	UnitCbdAContentDoseUnitOfMeasureName *string `json:"UnitCbdAContentDoseUnitOfMeasureName"`
	UnitCbdAContentUnitOfMeasureName *string `json:"UnitCbdAContentUnitOfMeasureName"`
	UnitCbdAPercent *float64 `json:"UnitCbdAPercent"`
	UnitCbdContent *float64 `json:"UnitCbdContent"`
	UnitCbdContentDose *float64 `json:"UnitCbdContentDose"`
	UnitCbdContentDoseUnitOfMeasureName *string `json:"UnitCbdContentDoseUnitOfMeasureName"`
	UnitCbdContentUnitOfMeasureName *string `json:"UnitCbdContentUnitOfMeasureName"`
	UnitCbdPercent *float64 `json:"UnitCbdPercent"`
	UnitOfMeasureName string `json:"UnitOfMeasureName"`
	UnitQuantity *string `json:"UnitQuantity"`
	UnitQuantityUnitOfMeasureName *string `json:"UnitQuantityUnitOfMeasureName"`
	UnitThcAContent *float64 `json:"UnitThcAContent"`
	UnitThcAContentDose *float64 `json:"UnitThcAContentDose"`
	UnitThcAContentDoseUnitOfMeasureId *int `json:"UnitThcAContentDoseUnitOfMeasureId"`
	UnitThcAContentDoseUnitOfMeasureName *string `json:"UnitThcAContentDoseUnitOfMeasureName"`
	UnitThcAContentUnitOfMeasureName *string `json:"UnitThcAContentUnitOfMeasureName"`
	UnitThcAPercent *float64 `json:"UnitThcAPercent"`
	UnitThcContent *float64 `json:"UnitThcContent"`
	UnitThcContentDose *float64 `json:"UnitThcContentDose"`
	UnitThcContentDoseUnitOfMeasureId *int `json:"UnitThcContentDoseUnitOfMeasureId"`
	UnitThcContentDoseUnitOfMeasureName *string `json:"UnitThcContentDoseUnitOfMeasureName"`
	UnitThcContentUnitOfMeasureName *string `json:"UnitThcContentUnitOfMeasureName"`
	UnitThcPercent *float64 `json:"UnitThcPercent"`
	UnitVolume *float64 `json:"UnitVolume"`
	UnitVolumeUnitOfMeasureName *string `json:"UnitVolumeUnitOfMeasureName"`
	UnitWeight *float64 `json:"UnitWeight"`
	UnitWeightUnitOfMeasureName *string `json:"UnitWeightUnitOfMeasureName"`
	Status string `json:"Status"`
	CanBeDecontaminated bool `json:"CanBeDecontaminated"`
	CanBeDestroyed bool `json:"CanBeDestroyed"`
	CanBeRemediated bool `json:"CanBeRemediated"`
	CanContainSeeds bool `json:"CanContainSeeds"`
	RequiresAdministrationMethod bool `json:"RequiresAdministrationMethod"`
	RequiresAllergens bool `json:"RequiresAllergens"`
	RequiresDescription bool `json:"RequiresDescription"`
	RequiresItemBrand bool `json:"RequiresItemBrand"`
	RequiresLabelPhotoDescription bool `json:"RequiresLabelPhotoDescription"`
	RequiresLabelPhotos int `json:"RequiresLabelPhotos"`
	RequiresNumberOfDoses bool `json:"RequiresNumberOfDoses"`
	RequiresPackagingPhotoDescription bool `json:"RequiresPackagingPhotoDescription"`
	RequiresPackagingPhotos int `json:"RequiresPackagingPhotos"`
	RequiresProductPDFDocuments int `json:"RequiresProductPDFDocuments"`
	RequiresProductPhotoDescription bool `json:"RequiresProductPhotoDescription"`
	RequiresProductPhotos int `json:"RequiresProductPhotos"`
	RequiresPublicIngredients bool `json:"RequiresPublicIngredients"`
	RequiresServingSize bool `json:"RequiresServingSize"`
	RequiresStrain bool `json:"RequiresStrain"`
	RequiresSupplyDurationDays bool `json:"RequiresSupplyDurationDays"`
	RequiresUnitCbdAContent bool `json:"RequiresUnitCbdAContent"`
	RequiresUnitCbdAContentDose bool `json:"RequiresUnitCbdAContentDose"`
	RequiresUnitCbdAPercent bool `json:"RequiresUnitCbdAPercent"`
	RequiresUnitCbdContent bool `json:"RequiresUnitCbdContent"`
	RequiresUnitCbdContentDose bool `json:"RequiresUnitCbdContentDose"`
	RequiresUnitCbdPercent bool `json:"RequiresUnitCbdPercent"`
	RequiresUnitThcAContent bool `json:"RequiresUnitThcAContent"`
	RequiresUnitThcAContentDose bool `json:"RequiresUnitThcAContentDose"`
	RequiresUnitThcAPercent bool `json:"RequiresUnitThcAPercent"`
	RequiresUnitThcContent bool `json:"RequiresUnitThcContent"`
	RequiresUnitThcContentDose bool `json:"RequiresUnitThcContentDose"`
	RequiresUnitThcPercent bool `json:"RequiresUnitThcPercent"`
	RequiresUnitVolume bool `json:"RequiresUnitVolume"`
	RequiresUnitWeight bool `json:"RequiresUnitWeight"`
}

