package models

type Package struct {
	Ids []float64 `json:"Ids"`
	Warnings *string `json:"Warnings"`
	ArchivedDate *string `json:"ArchivedDate"`
	ContainsDecontaminatedProduct bool `json:"ContainsDecontaminatedProduct"`
	ContainsRemediatedProduct bool `json:"ContainsRemediatedProduct"`
	DecontaminationDate *string `json:"DecontaminationDate"`
	ExpirationDate *string `json:"ExpirationDate"`
	ExternalId *int `json:"ExternalId"`
	FinishedDate *string `json:"FinishedDate"`
	Id int `json:"Id"`
	InitialLabTestingState string `json:"InitialLabTestingState"`
	IsDonation bool `json:"IsDonation"`
	IsDonationPersistent bool `json:"IsDonationPersistent"`
	IsFinished bool `json:"IsFinished"`
	IsOnHold bool `json:"IsOnHold"`
	IsOnHoldCombined bool `json:"IsOnHoldCombined"`
	IsOnInvestigation bool `json:"IsOnInvestigation"`
	IsOnInvestigationHold bool `json:"IsOnInvestigationHold"`
	IsOnInvestigationRecall bool `json:"IsOnInvestigationRecall"`
	IsOnRecall *bool `json:"IsOnRecall"`
	IsOnRecallCombined bool `json:"IsOnRecallCombined"`
	IsOnRetailerDelivery bool `json:"IsOnRetailerDelivery"`
	IsProcessValidationTestingSample bool `json:"IsProcessValidationTestingSample"`
	IsProductionBatch bool `json:"IsProductionBatch"`
	IsTestingSample bool `json:"IsTestingSample"`
	IsTradeSample bool `json:"IsTradeSample"`
	IsTradeSamplePersistent bool `json:"IsTradeSamplePersistent"`
	Item PackageItem `json:"Item"`
	ItemFromFacilityLicenseNumber *string `json:"ItemFromFacilityLicenseNumber"`
	ItemFromFacilityName *string `json:"ItemFromFacilityName"`
	LabTestResultExpirationDateTime *string `json:"LabTestResultExpirationDateTime"`
	LabTestStage *string `json:"LabTestStage"`
	LabTestStageId *int `json:"LabTestStageId"`
	LabTestingPerformedDate *string `json:"LabTestingPerformedDate"`
	LabTestingRecordedDate *string `json:"LabTestingRecordedDate"`
	LabTestingState string `json:"LabTestingState"`
	LabTestingStateDate string `json:"LabTestingStateDate"`
	Label string `json:"Label"`
	LabelsLastGeneratedDateTime *string `json:"LabelsLastGeneratedDateTime"`
	LastModified string `json:"LastModified"`
	LocationId *int `json:"LocationId"`
	LocationName *string `json:"LocationName"`
	LocationTypeName *string `json:"LocationTypeName"`
	Note *string `json:"Note"`
	OriginalPackageQuantity int `json:"OriginalPackageQuantity"`
	PackageForProductDestruction *string `json:"PackageForProductDestruction"`
	PackageType string `json:"PackageType"`
	PackagedDate string `json:"PackagedDate"`
	PatientLicenseNumber *string `json:"PatientLicenseNumber"`
	ProductLabel PackageProductLabel `json:"ProductLabel"`
	ProductRequiresDecontamination bool `json:"ProductRequiresDecontamination"`
	ProductRequiresRemediation bool `json:"ProductRequiresRemediation"`
	ProductionBatchNumber *string `json:"ProductionBatchNumber"`
	Quantity int `json:"Quantity"`
	ReceivedDateTime *string `json:"ReceivedDateTime"`
	ReceivedFromFacilityLicenseNumber *string `json:"ReceivedFromFacilityLicenseNumber"`
	ReceivedFromFacilityName *string `json:"ReceivedFromFacilityName"`
	ReceivedFromManifestNumber *string `json:"ReceivedFromManifestNumber"`
	RemediationDate *string `json:"RemediationDate"`
	SellByDate *string `json:"SellByDate"`
	SourceHarvestCount int `json:"SourceHarvestCount"`
	SourceHarvestNames *string `json:"SourceHarvestNames"`
	SourcePackageCount int `json:"SourcePackageCount"`
	SourcePackageIsDonation bool `json:"SourcePackageIsDonation"`
	SourcePackageIsTradeSample bool `json:"SourcePackageIsTradeSample"`
	SourcePackageLabels *string `json:"SourcePackageLabels"`
	SourceProcessingJobCount int `json:"SourceProcessingJobCount"`
	SourceProductionBatchNumbers *string `json:"SourceProductionBatchNumbers"`
	SublocationId *int `json:"SublocationId"`
	SublocationName *string `json:"SublocationName"`
	UnitOfMeasureAbbreviation string `json:"UnitOfMeasureAbbreviation"`
	UnitOfMeasureName string `json:"UnitOfMeasureName"`
	UseByDate *string `json:"UseByDate"`
	CurrentPage int `json:"CurrentPage"`
	Data []PackageData `json:"Data"`
	Page int `json:"Page"`
	PageSize int `json:"PageSize"`
	RecordsOnPage int `json:"RecordsOnPage"`
	Total int `json:"Total"`
	TotalPages int `json:"TotalPages"`
	TotalRecords int `json:"TotalRecords"`
	Name string `json:"Name"`
	RequiresImmatureWasteWeight bool `json:"RequiresImmatureWasteWeight"`
	RequiresMatureWasteWeight bool `json:"RequiresMatureWasteWeight"`
	RequiresNote bool `json:"RequiresNote"`
	RequiresWasteWeight bool `json:"RequiresWasteWeight"`
	HarvestStartDate string `json:"HarvestStartDate"`
	HarvestedByFacilityLicenseNumber string `json:"HarvestedByFacilityLicenseNumber"`
	HarvestedByFacilityName string `json:"HarvestedByFacilityName"`
}

type PackageData struct {
	ArchivedDate *string `json:"ArchivedDate"`
	ContainsDecontaminatedProduct bool `json:"ContainsDecontaminatedProduct"`
	ContainsRemediatedProduct bool `json:"ContainsRemediatedProduct"`
	DecontaminationDate *string `json:"DecontaminationDate"`
	ExpirationDate *string `json:"ExpirationDate"`
	ExternalId *int `json:"ExternalId"`
	FinishedDate *string `json:"FinishedDate"`
	Id int `json:"Id"`
	InitialLabTestingState string `json:"InitialLabTestingState"`
	IsDonation bool `json:"IsDonation"`
	IsDonationPersistent bool `json:"IsDonationPersistent"`
	IsFinished bool `json:"IsFinished"`
	IsOnHold bool `json:"IsOnHold"`
	IsOnHoldCombined bool `json:"IsOnHoldCombined"`
	IsOnInvestigation bool `json:"IsOnInvestigation"`
	IsOnInvestigationHold bool `json:"IsOnInvestigationHold"`
	IsOnInvestigationRecall bool `json:"IsOnInvestigationRecall"`
	IsOnRecall *bool `json:"IsOnRecall"`
	IsOnRecallCombined bool `json:"IsOnRecallCombined"`
	IsOnRetailerDelivery bool `json:"IsOnRetailerDelivery"`
	IsProcessValidationTestingSample bool `json:"IsProcessValidationTestingSample"`
	IsProductionBatch bool `json:"IsProductionBatch"`
	IsTestingSample bool `json:"IsTestingSample"`
	IsTradeSample bool `json:"IsTradeSample"`
	IsTradeSamplePersistent bool `json:"IsTradeSamplePersistent"`
	Item PackageDataItem `json:"Item"`
	ItemFromFacilityLicenseNumber *string `json:"ItemFromFacilityLicenseNumber"`
	ItemFromFacilityName *string `json:"ItemFromFacilityName"`
	LabTestResultExpirationDateTime *string `json:"LabTestResultExpirationDateTime"`
	LabTestStage *string `json:"LabTestStage"`
	LabTestStageId *int `json:"LabTestStageId"`
	LabTestingPerformedDate *string `json:"LabTestingPerformedDate"`
	LabTestingRecordedDate *string `json:"LabTestingRecordedDate"`
	LabTestingState string `json:"LabTestingState"`
	LabTestingStateDate string `json:"LabTestingStateDate"`
	Label string `json:"Label"`
	LabelsLastGeneratedDateTime *string `json:"LabelsLastGeneratedDateTime"`
	LastModified string `json:"LastModified"`
	LocationId *int `json:"LocationId"`
	LocationName *string `json:"LocationName"`
	LocationTypeName *string `json:"LocationTypeName"`
	Note *string `json:"Note"`
	OriginalPackageQuantity int `json:"OriginalPackageQuantity"`
	PackageForProductDestruction *string `json:"PackageForProductDestruction"`
	PackageType string `json:"PackageType"`
	PackagedDate string `json:"PackagedDate"`
	PatientLicenseNumber *string `json:"PatientLicenseNumber"`
	ProductLabel PackageDataProductLabel `json:"ProductLabel"`
	ProductRequiresDecontamination bool `json:"ProductRequiresDecontamination"`
	ProductRequiresRemediation bool `json:"ProductRequiresRemediation"`
	ProductionBatchNumber *string `json:"ProductionBatchNumber"`
	Quantity int `json:"Quantity"`
	ReceivedDateTime *string `json:"ReceivedDateTime"`
	ReceivedFromFacilityLicenseNumber *string `json:"ReceivedFromFacilityLicenseNumber"`
	ReceivedFromFacilityName *string `json:"ReceivedFromFacilityName"`
	ReceivedFromManifestNumber *string `json:"ReceivedFromManifestNumber"`
	RemediationDate *string `json:"RemediationDate"`
	SellByDate *string `json:"SellByDate"`
	SourceHarvestCount int `json:"SourceHarvestCount"`
	SourceHarvestNames *string `json:"SourceHarvestNames"`
	SourcePackageCount int `json:"SourcePackageCount"`
	SourcePackageIsDonation bool `json:"SourcePackageIsDonation"`
	SourcePackageIsTradeSample bool `json:"SourcePackageIsTradeSample"`
	SourcePackageLabels *string `json:"SourcePackageLabels"`
	SourceProcessingJobCount int `json:"SourceProcessingJobCount"`
	SourceProductionBatchNumbers *string `json:"SourceProductionBatchNumbers"`
	SublocationId *int `json:"SublocationId"`
	SublocationName *string `json:"SublocationName"`
	UnitOfMeasureAbbreviation string `json:"UnitOfMeasureAbbreviation"`
	UnitOfMeasureName string `json:"UnitOfMeasureName"`
	UseByDate *string `json:"UseByDate"`
	Name string `json:"Name"`
	RequiresImmatureWasteWeight bool `json:"RequiresImmatureWasteWeight"`
	RequiresMatureWasteWeight bool `json:"RequiresMatureWasteWeight"`
	RequiresNote bool `json:"RequiresNote"`
	RequiresWasteWeight bool `json:"RequiresWasteWeight"`
	LabFacilityLicenseNumber *string `json:"LabFacilityLicenseNumber"`
	LabFacilityName *string `json:"LabFacilityName"`
	OverallPassed bool `json:"OverallPassed"`
	ResultReleaseDateTime string `json:"ResultReleaseDateTime"`
	ResultReleased bool `json:"ResultReleased"`
	TestComment *string `json:"TestComment"`
	TestInformationalOnly bool `json:"TestInformationalOnly"`
	TestPassed bool `json:"TestPassed"`
	TestPerformedDate string `json:"TestPerformedDate"`
	TestResultLevel float64 `json:"TestResultLevel"`
	TestTypeName string `json:"TestTypeName"`
	ActualDepartureDateTime string `json:"ActualDepartureDateTime"`
	GrossUnitOfWeightAbbreviation string `json:"GrossUnitOfWeightAbbreviation"`
	GrossWeight float64 `json:"GrossWeight"`
	ItemStrainName string `json:"ItemStrainName"`
	LabTestingStateName string `json:"LabTestingStateName"`
	ManifestNumber string `json:"ManifestNumber"`
	PackageId int `json:"PackageId"`
	PackageLabel string `json:"PackageLabel"`
	ProcessingJobTypeName string `json:"ProcessingJobTypeName"`
	ProductCategoryName string `json:"ProductCategoryName"`
	ProductName string `json:"ProductName"`
	ReceivedQuantity int `json:"ReceivedQuantity"`
	ReceivedUnitOfMeasureAbbreviation string `json:"ReceivedUnitOfMeasureAbbreviation"`
	ReceiverWholesalePrice float64 `json:"ReceiverWholesalePrice"`
	RecipientFacilityLicenseNumber string `json:"RecipientFacilityLicenseNumber"`
	RecipientFacilityName string `json:"RecipientFacilityName"`
	ShipmentPackageStateName string `json:"ShipmentPackageStateName"`
	ShippedQuantity int `json:"ShippedQuantity"`
	ShippedUnitOfMeasureAbbreviation string `json:"ShippedUnitOfMeasureAbbreviation"`
	ShipperWholesalePrice float64 `json:"ShipperWholesalePrice"`
}

type PackageDataItem struct {
	AdministrationMethod *string `json:"AdministrationMethod"`
	Allergens *string `json:"Allergens"`
	ApprovalStatus int `json:"ApprovalStatus"`
	ApprovalStatusDateTime string `json:"ApprovalStatusDateTime"`
	DefaultLabTestingState int `json:"DefaultLabTestingState"`
	Description *string `json:"Description"`
	GlobalProductName *string `json:"GlobalProductName"`
	GlobalProductNumber *string `json:"GlobalProductNumber"`
	HasExpirationDate bool `json:"HasExpirationDate"`
	HasSellByDate bool `json:"HasSellByDate"`
	HasUseByDate bool `json:"HasUseByDate"`
	Id int `json:"Id"`
	IsExpirationDateRequired bool `json:"IsExpirationDateRequired"`
	IsSellByDateRequired bool `json:"IsSellByDateRequired"`
	IsUseByDateRequired bool `json:"IsUseByDateRequired"`
	IsUsed bool `json:"IsUsed"`
	ItemBrandId int `json:"ItemBrandId"`
	ItemBrandName *string `json:"ItemBrandName"`
	LabTestBatchNames []interface{} `json:"LabTestBatchNames"`
	LabelImages []interface{} `json:"LabelImages"`
	LabelPhotoDescription *string `json:"LabelPhotoDescription"`
	Name string `json:"Name"`
	NumberOfDoses *string `json:"NumberOfDoses"`
	PackagingImages []interface{} `json:"PackagingImages"`
	PackagingPhotoDescription *string `json:"PackagingPhotoDescription"`
	ProcessingJobCategoryName *string `json:"ProcessingJobCategoryName"`
	ProcessingJobTypeName *string `json:"ProcessingJobTypeName"`
	ProductBrandName *string `json:"ProductBrandName"`
	ProductCategoryName string `json:"ProductCategoryName"`
	ProductCategoryType int `json:"ProductCategoryType"`
	ProductImages []interface{} `json:"ProductImages"`
	ProductPDFDocuments []interface{} `json:"ProductPDFDocuments"`
	ProductPhotoDescription *string `json:"ProductPhotoDescription"`
	PublicIngredients *string `json:"PublicIngredients"`
	QuantityType int `json:"QuantityType"`
	ServingSize *string `json:"ServingSize"`
	StrainId *int `json:"StrainId"`
	StrainName *string `json:"StrainName"`
	UnitCbdAContent *float64 `json:"UnitCbdAContent"`
	UnitCbdAContentDose *float64 `json:"UnitCbdAContentDose"`
	UnitCbdAContentDoseUnitOfMeasureName *string `json:"UnitCbdAContentDoseUnitOfMeasureName"`
	UnitCbdAContentUnitOfMeasureName *string `json:"UnitCbdAContentUnitOfMeasureName"`
	UnitCbdAPercent *float64 `json:"UnitCbdAPercent"`
	UnitCbdContent *float64 `json:"UnitCbdContent"`
	UnitCbdContentDose *float64 `json:"UnitCbdContentDose"`
	UnitCbdContentDoseUnitOfMeasureName *string `json:"UnitCbdContentDoseUnitOfMeasureName"`
	UnitCbdContentUnitOfMeasureName *string `json:"UnitCbdContentUnitOfMeasureName"`
	UnitCbdPercent *float64 `json:"UnitCbdPercent"`
	UnitOfMeasureName *string `json:"UnitOfMeasureName"`
	UnitQuantity *string `json:"UnitQuantity"`
	UnitQuantityUnitOfMeasureName *string `json:"UnitQuantityUnitOfMeasureName"`
	UnitThcAContent *float64 `json:"UnitThcAContent"`
	UnitThcAContentDose *float64 `json:"UnitThcAContentDose"`
	UnitThcAContentDoseUnitOfMeasureId *int `json:"UnitThcAContentDoseUnitOfMeasureId"`
	UnitThcAContentDoseUnitOfMeasureName *string `json:"UnitThcAContentDoseUnitOfMeasureName"`
	UnitThcAContentUnitOfMeasureName *string `json:"UnitThcAContentUnitOfMeasureName"`
	UnitThcAPercent *float64 `json:"UnitThcAPercent"`
	UnitThcContent *float64 `json:"UnitThcContent"`
	UnitThcContentDose *float64 `json:"UnitThcContentDose"`
	UnitThcContentDoseUnitOfMeasureId *int `json:"UnitThcContentDoseUnitOfMeasureId"`
	UnitThcContentDoseUnitOfMeasureName *string `json:"UnitThcContentDoseUnitOfMeasureName"`
	UnitThcContentUnitOfMeasureName *string `json:"UnitThcContentUnitOfMeasureName"`
	UnitThcPercent *float64 `json:"UnitThcPercent"`
	UnitVolume *float64 `json:"UnitVolume"`
	UnitVolumeUnitOfMeasureName *string `json:"UnitVolumeUnitOfMeasureName"`
	UnitWeight *float64 `json:"UnitWeight"`
	UnitWeightUnitOfMeasureName *string `json:"UnitWeightUnitOfMeasureName"`
}

type PackageDataProductLabel struct {
	IsActive bool `json:"IsActive"`
	IsChildFromParentWithLabel bool `json:"IsChildFromParentWithLabel"`
	IsDiscontinued bool `json:"IsDiscontinued"`
	LastLabelGenerationDate *string `json:"LastLabelGenerationDate"`
	PackageId int `json:"PackageId"`
	QrCount int `json:"QrCount"`
	TagId *int `json:"TagId"`
}

type PackageItem struct {
	AdministrationMethod *string `json:"AdministrationMethod"`
	Allergens *string `json:"Allergens"`
	ApprovalStatus int `json:"ApprovalStatus"`
	ApprovalStatusDateTime string `json:"ApprovalStatusDateTime"`
	DefaultLabTestingState int `json:"DefaultLabTestingState"`
	Description *string `json:"Description"`
	GlobalProductName *string `json:"GlobalProductName"`
	GlobalProductNumber *string `json:"GlobalProductNumber"`
	HasExpirationDate bool `json:"HasExpirationDate"`
	HasSellByDate bool `json:"HasSellByDate"`
	HasUseByDate bool `json:"HasUseByDate"`
	Id int `json:"Id"`
	IsExpirationDateRequired bool `json:"IsExpirationDateRequired"`
	IsSellByDateRequired bool `json:"IsSellByDateRequired"`
	IsUseByDateRequired bool `json:"IsUseByDateRequired"`
	IsUsed bool `json:"IsUsed"`
	ItemBrandId int `json:"ItemBrandId"`
	ItemBrandName *string `json:"ItemBrandName"`
	LabTestBatchNames []interface{} `json:"LabTestBatchNames"`
	LabelImages []interface{} `json:"LabelImages"`
	LabelPhotoDescription *string `json:"LabelPhotoDescription"`
	Name string `json:"Name"`
	NumberOfDoses *string `json:"NumberOfDoses"`
	PackagingImages []interface{} `json:"PackagingImages"`
	PackagingPhotoDescription *string `json:"PackagingPhotoDescription"`
	ProcessingJobCategoryName *string `json:"ProcessingJobCategoryName"`
	ProcessingJobTypeName *string `json:"ProcessingJobTypeName"`
	ProductBrandName *string `json:"ProductBrandName"`
	ProductCategoryName string `json:"ProductCategoryName"`
	ProductCategoryType int `json:"ProductCategoryType"`
	ProductImages []interface{} `json:"ProductImages"`
	ProductPDFDocuments []interface{} `json:"ProductPDFDocuments"`
	ProductPhotoDescription *string `json:"ProductPhotoDescription"`
	PublicIngredients *string `json:"PublicIngredients"`
	QuantityType int `json:"QuantityType"`
	ServingSize *string `json:"ServingSize"`
	StrainId *int `json:"StrainId"`
	StrainName *string `json:"StrainName"`
	UnitCbdAContent *float64 `json:"UnitCbdAContent"`
	UnitCbdAContentDose *float64 `json:"UnitCbdAContentDose"`
	UnitCbdAContentDoseUnitOfMeasureName *string `json:"UnitCbdAContentDoseUnitOfMeasureName"`
	UnitCbdAContentUnitOfMeasureName *string `json:"UnitCbdAContentUnitOfMeasureName"`
	UnitCbdAPercent *float64 `json:"UnitCbdAPercent"`
	UnitCbdContent *float64 `json:"UnitCbdContent"`
	UnitCbdContentDose *float64 `json:"UnitCbdContentDose"`
	UnitCbdContentDoseUnitOfMeasureName *string `json:"UnitCbdContentDoseUnitOfMeasureName"`
	UnitCbdContentUnitOfMeasureName *string `json:"UnitCbdContentUnitOfMeasureName"`
	UnitCbdPercent *float64 `json:"UnitCbdPercent"`
	UnitOfMeasureName *string `json:"UnitOfMeasureName"`
	UnitQuantity *string `json:"UnitQuantity"`
	UnitQuantityUnitOfMeasureName *string `json:"UnitQuantityUnitOfMeasureName"`
	UnitThcAContent *float64 `json:"UnitThcAContent"`
	UnitThcAContentDose *float64 `json:"UnitThcAContentDose"`
	UnitThcAContentDoseUnitOfMeasureId *int `json:"UnitThcAContentDoseUnitOfMeasureId"`
	UnitThcAContentDoseUnitOfMeasureName *string `json:"UnitThcAContentDoseUnitOfMeasureName"`
	UnitThcAContentUnitOfMeasureName *string `json:"UnitThcAContentUnitOfMeasureName"`
	UnitThcAPercent *float64 `json:"UnitThcAPercent"`
	UnitThcContent *float64 `json:"UnitThcContent"`
	UnitThcContentDose *float64 `json:"UnitThcContentDose"`
	UnitThcContentDoseUnitOfMeasureId *int `json:"UnitThcContentDoseUnitOfMeasureId"`
	UnitThcContentDoseUnitOfMeasureName *string `json:"UnitThcContentDoseUnitOfMeasureName"`
	UnitThcContentUnitOfMeasureName *string `json:"UnitThcContentUnitOfMeasureName"`
	UnitThcPercent *float64 `json:"UnitThcPercent"`
	UnitVolume *float64 `json:"UnitVolume"`
	UnitVolumeUnitOfMeasureName *string `json:"UnitVolumeUnitOfMeasureName"`
	UnitWeight *float64 `json:"UnitWeight"`
	UnitWeightUnitOfMeasureName *string `json:"UnitWeightUnitOfMeasureName"`
}

type PackageProductLabel struct {
	IsActive bool `json:"IsActive"`
	IsChildFromParentWithLabel bool `json:"IsChildFromParentWithLabel"`
	IsDiscontinued bool `json:"IsDiscontinued"`
	LastLabelGenerationDate *string `json:"LastLabelGenerationDate"`
	PackageId int `json:"PackageId"`
	QrCount int `json:"QrCount"`
	TagId *int `json:"TagId"`
}

