package models

type Plant struct {
	Ids []float64 `json:"Ids"`
	Warnings *string `json:"Warnings"`
	ClonedCount *int `json:"ClonedCount"`
	DescendedCount *int `json:"DescendedCount"`
	DestroyedByUserName *string `json:"DestroyedByUserName"`
	DestroyedDate *string `json:"DestroyedDate"`
	DestroyedNote *string `json:"DestroyedNote"`
	FloweringDate *string `json:"FloweringDate"`
	GroupTagTypeMax int `json:"GroupTagTypeMax"`
	GrowthPhase string `json:"GrowthPhase"`
	HarvestCount int `json:"HarvestCount"`
	HarvestId *int `json:"HarvestId"`
	HarvestedDate *string `json:"HarvestedDate"`
	HarvestedUnitOfWeightAbbreviation *string `json:"HarvestedUnitOfWeightAbbreviation"`
	HarvestedUnitOfWeightName *string `json:"HarvestedUnitOfWeightName"`
	HarvestedWetWeight *float64 `json:"HarvestedWetWeight"`
	Id int `json:"Id"`
	IsOnHold bool `json:"IsOnHold"`
	IsOnInvestigation bool `json:"IsOnInvestigation"`
	IsOnInvestigationHold bool `json:"IsOnInvestigationHold"`
	IsOnInvestigationRecall bool `json:"IsOnInvestigationRecall"`
	Label string `json:"Label"`
	LastModified string `json:"LastModified"`
	LocationId int `json:"LocationId"`
	LocationName string `json:"LocationName"`
	LocationTypeName *string `json:"LocationTypeName"`
	MotherPlantDate *string `json:"MotherPlantDate"`
	PatientLicenseNumber *string `json:"PatientLicenseNumber"`
	PlantBatchId int `json:"PlantBatchId"`
	PlantBatchName string `json:"PlantBatchName"`
	PlantBatchTypeId int `json:"PlantBatchTypeId"`
	PlantBatchTypeName string `json:"PlantBatchTypeName"`
	PlantedDate string `json:"PlantedDate"`
	State string `json:"State"`
	StrainId int `json:"StrainId"`
	StrainName string `json:"StrainName"`
	SublocationId *int `json:"SublocationId"`
	SublocationName *string `json:"SublocationName"`
	SurvivedCount *int `json:"SurvivedCount"`
	TagTypeMax int `json:"TagTypeMax"`
	VegetativeDate string `json:"VegetativeDate"`
	AdditiveTypeName *string `json:"AdditiveTypeName"`
	AmountUnitOfMeasure string `json:"AmountUnitOfMeasure"`
	ApplicationDevice string `json:"ApplicationDevice"`
	EpaRegistrationNumber *string `json:"EpaRegistrationNumber"`
	Note *string `json:"Note"`
	PlantCount int `json:"PlantCount"`
	ProductSupplier string `json:"ProductSupplier"`
	ProductTradeName string `json:"ProductTradeName"`
	Rate *string `json:"Rate"`
	RestrictiveEntryIntervalQuantityDescription *string `json:"RestrictiveEntryIntervalQuantityDescription"`
	RestrictiveEntryIntervalTimeDescription *string `json:"RestrictiveEntryIntervalTimeDescription"`
	TotalAmountApplied int `json:"TotalAmountApplied"`
	Volume *float64 `json:"Volume"`
	CurrentPage int `json:"CurrentPage"`
	Data []PlantData `json:"Data"`
	Page int `json:"Page"`
	PageSize int `json:"PageSize"`
	RecordsOnPage int `json:"RecordsOnPage"`
	Total int `json:"Total"`
	TotalPages int `json:"TotalPages"`
	TotalRecords int `json:"TotalRecords"`
	ForPlants bool `json:"ForPlants"`
	ForProductDestruction bool `json:"ForProductDestruction"`
	Name string `json:"Name"`
	RequiresImmatureWasteWeight bool `json:"RequiresImmatureWasteWeight"`
	RequiresMatureWasteWeight bool `json:"RequiresMatureWasteWeight"`
	RequiresNote bool `json:"RequiresNote"`
	RequiresWasteWeight bool `json:"RequiresWasteWeight"`
}

type PlantData struct {
	AdditiveTypeName *string `json:"AdditiveTypeName"`
	AmountUnitOfMeasure string `json:"AmountUnitOfMeasure"`
	ApplicationDevice string `json:"ApplicationDevice"`
	EpaRegistrationNumber *string `json:"EpaRegistrationNumber"`
	Note *string `json:"Note"`
	PlantBatchId *int `json:"PlantBatchId"`
	PlantBatchName *string `json:"PlantBatchName"`
	PlantCount int `json:"PlantCount"`
	ProductSupplier string `json:"ProductSupplier"`
	ProductTradeName string `json:"ProductTradeName"`
	Rate *string `json:"Rate"`
	RestrictiveEntryIntervalQuantityDescription *string `json:"RestrictiveEntryIntervalQuantityDescription"`
	RestrictiveEntryIntervalTimeDescription *string `json:"RestrictiveEntryIntervalTimeDescription"`
	TotalAmountApplied int `json:"TotalAmountApplied"`
	Volume *float64 `json:"Volume"`
	ClonedCount *int `json:"ClonedCount"`
	DescendedCount *int `json:"DescendedCount"`
	DestroyedByUserName *string `json:"DestroyedByUserName"`
	DestroyedDate *string `json:"DestroyedDate"`
	DestroyedNote *string `json:"DestroyedNote"`
	FloweringDate string `json:"FloweringDate"`
	GroupTagTypeMax int `json:"GroupTagTypeMax"`
	GrowthPhase string `json:"GrowthPhase"`
	HarvestCount int `json:"HarvestCount"`
	HarvestId *int `json:"HarvestId"`
	HarvestedDate *string `json:"HarvestedDate"`
	HarvestedUnitOfWeightAbbreviation *string `json:"HarvestedUnitOfWeightAbbreviation"`
	HarvestedUnitOfWeightName *string `json:"HarvestedUnitOfWeightName"`
	HarvestedWetWeight *float64 `json:"HarvestedWetWeight"`
	Id int `json:"Id"`
	IsOnHold bool `json:"IsOnHold"`
	IsOnInvestigation bool `json:"IsOnInvestigation"`
	IsOnInvestigationHold bool `json:"IsOnInvestigationHold"`
	IsOnInvestigationRecall bool `json:"IsOnInvestigationRecall"`
	Label string `json:"Label"`
	LastModified string `json:"LastModified"`
	LocationId int `json:"LocationId"`
	LocationName string `json:"LocationName"`
	LocationTypeName *string `json:"LocationTypeName"`
	MotherPlantDate *string `json:"MotherPlantDate"`
	PatientLicenseNumber *string `json:"PatientLicenseNumber"`
	PlantBatchTypeId int `json:"PlantBatchTypeId"`
	PlantBatchTypeName string `json:"PlantBatchTypeName"`
	PlantedDate string `json:"PlantedDate"`
	State string `json:"State"`
	StrainId int `json:"StrainId"`
	StrainName string `json:"StrainName"`
	SublocationId *int `json:"SublocationId"`
	SublocationName *string `json:"SublocationName"`
	SurvivedCount *int `json:"SurvivedCount"`
	TagTypeMax int `json:"TagTypeMax"`
	VegetativeDate string `json:"VegetativeDate"`
	PlantWasteNumber string `json:"PlantWasteNumber"`
	WasteDate string `json:"WasteDate"`
	WasteMethodName string `json:"WasteMethodName"`
	WasteReasonName string `json:"WasteReasonName"`
	WasteUnitOfMeasureName string `json:"WasteUnitOfMeasureName"`
	WasteWeight float64 `json:"WasteWeight"`
	ForPlants bool `json:"ForPlants"`
	ForProductDestruction bool `json:"ForProductDestruction"`
	Name string `json:"Name"`
	ArchivedDate *string `json:"ArchivedDate"`
	ContainsDecontaminatedProduct bool `json:"ContainsDecontaminatedProduct"`
	ContainsRemediatedProduct bool `json:"ContainsRemediatedProduct"`
	DecontaminationDate *string `json:"DecontaminationDate"`
	ExpirationDate *string `json:"ExpirationDate"`
	ExternalId *int `json:"ExternalId"`
	FinishedDate *string `json:"FinishedDate"`
	InitialLabTestingState string `json:"InitialLabTestingState"`
	IsDonation bool `json:"IsDonation"`
	IsDonationPersistent bool `json:"IsDonationPersistent"`
	IsFinished bool `json:"IsFinished"`
	IsOnHoldCombined bool `json:"IsOnHoldCombined"`
	IsOnRecall *bool `json:"IsOnRecall"`
	IsOnRecallCombined bool `json:"IsOnRecallCombined"`
	IsOnRetailerDelivery bool `json:"IsOnRetailerDelivery"`
	IsProcessValidationTestingSample bool `json:"IsProcessValidationTestingSample"`
	IsProductionBatch bool `json:"IsProductionBatch"`
	IsTestingSample bool `json:"IsTestingSample"`
	IsTradeSample bool `json:"IsTradeSample"`
	IsTradeSamplePersistent bool `json:"IsTradeSamplePersistent"`
	Item PlantDataItem `json:"Item"`
	ItemFromFacilityLicenseNumber *string `json:"ItemFromFacilityLicenseNumber"`
	ItemFromFacilityName *string `json:"ItemFromFacilityName"`
	LabTestResultExpirationDateTime *string `json:"LabTestResultExpirationDateTime"`
	LabTestStage *string `json:"LabTestStage"`
	LabTestStageId *int `json:"LabTestStageId"`
	LabTestingPerformedDate *string `json:"LabTestingPerformedDate"`
	LabTestingRecordedDate *string `json:"LabTestingRecordedDate"`
	LabTestingState string `json:"LabTestingState"`
	LabTestingStateDate string `json:"LabTestingStateDate"`
	LabelsLastGeneratedDateTime *string `json:"LabelsLastGeneratedDateTime"`
	OriginalPackageQuantity int `json:"OriginalPackageQuantity"`
	PackageForProductDestruction *string `json:"PackageForProductDestruction"`
	PackageType string `json:"PackageType"`
	PackagedDate string `json:"PackagedDate"`
	ProductLabel PlantDataProductLabel `json:"ProductLabel"`
	ProductRequiresDecontamination bool `json:"ProductRequiresDecontamination"`
	ProductRequiresRemediation bool `json:"ProductRequiresRemediation"`
	ProductionBatchNumber *string `json:"ProductionBatchNumber"`
	Quantity int `json:"Quantity"`
	ReceivedDateTime *string `json:"ReceivedDateTime"`
	ReceivedFromFacilityLicenseNumber *string `json:"ReceivedFromFacilityLicenseNumber"`
	ReceivedFromFacilityName *string `json:"ReceivedFromFacilityName"`
	ReceivedFromManifestNumber *string `json:"ReceivedFromManifestNumber"`
	RemediationDate *string `json:"RemediationDate"`
	SellByDate *string `json:"SellByDate"`
	SourceHarvestCount int `json:"SourceHarvestCount"`
	SourceHarvestNames *string `json:"SourceHarvestNames"`
	SourcePackageCount int `json:"SourcePackageCount"`
	SourcePackageIsDonation bool `json:"SourcePackageIsDonation"`
	SourcePackageIsTradeSample bool `json:"SourcePackageIsTradeSample"`
	SourcePackageLabels *string `json:"SourcePackageLabels"`
	SourceProcessingJobCount int `json:"SourceProcessingJobCount"`
	SourceProductionBatchNumbers *string `json:"SourceProductionBatchNumbers"`
	UnitOfMeasureAbbreviation string `json:"UnitOfMeasureAbbreviation"`
	UnitOfMeasureName string `json:"UnitOfMeasureName"`
	UseByDate *string `json:"UseByDate"`
	PlantId int `json:"PlantId"`
	PlantWasteId int `json:"PlantWasteId"`
	StateName string `json:"StateName"`
	WasteAmount int `json:"WasteAmount"`
	WasteUnitOfMeasureAbbreviation string `json:"WasteUnitOfMeasureAbbreviation"`
	RequiresImmatureWasteWeight bool `json:"RequiresImmatureWasteWeight"`
	RequiresMatureWasteWeight bool `json:"RequiresMatureWasteWeight"`
	RequiresNote bool `json:"RequiresNote"`
	RequiresWasteWeight bool `json:"RequiresWasteWeight"`
}

type PlantDataItem struct {
	AdministrationMethod *string `json:"AdministrationMethod"`
	Allergens *string `json:"Allergens"`
	ApprovalStatus int `json:"ApprovalStatus"`
	ApprovalStatusDateTime string `json:"ApprovalStatusDateTime"`
	DefaultLabTestingState int `json:"DefaultLabTestingState"`
	Description *string `json:"Description"`
	GlobalProductName *string `json:"GlobalProductName"`
	GlobalProductNumber *string `json:"GlobalProductNumber"`
	HasExpirationDate bool `json:"HasExpirationDate"`
	HasSellByDate bool `json:"HasSellByDate"`
	HasUseByDate bool `json:"HasUseByDate"`
	Id int `json:"Id"`
	IsExpirationDateRequired bool `json:"IsExpirationDateRequired"`
	IsSellByDateRequired bool `json:"IsSellByDateRequired"`
	IsUseByDateRequired bool `json:"IsUseByDateRequired"`
	IsUsed bool `json:"IsUsed"`
	ItemBrandId int `json:"ItemBrandId"`
	ItemBrandName *string `json:"ItemBrandName"`
	LabTestBatchNames []interface{} `json:"LabTestBatchNames"`
	LabelImages []interface{} `json:"LabelImages"`
	LabelPhotoDescription *string `json:"LabelPhotoDescription"`
	Name string `json:"Name"`
	NumberOfDoses *string `json:"NumberOfDoses"`
	PackagingImages []interface{} `json:"PackagingImages"`
	PackagingPhotoDescription *string `json:"PackagingPhotoDescription"`
	ProcessingJobCategoryName *string `json:"ProcessingJobCategoryName"`
	ProcessingJobTypeName *string `json:"ProcessingJobTypeName"`
	ProductBrandName *string `json:"ProductBrandName"`
	ProductCategoryName string `json:"ProductCategoryName"`
	ProductCategoryType int `json:"ProductCategoryType"`
	ProductImages []interface{} `json:"ProductImages"`
	ProductPDFDocuments []interface{} `json:"ProductPDFDocuments"`
	ProductPhotoDescription *string `json:"ProductPhotoDescription"`
	PublicIngredients *string `json:"PublicIngredients"`
	QuantityType int `json:"QuantityType"`
	ServingSize *string `json:"ServingSize"`
	StrainId *int `json:"StrainId"`
	StrainName *string `json:"StrainName"`
	UnitCbdAContent *float64 `json:"UnitCbdAContent"`
	UnitCbdAContentDose *float64 `json:"UnitCbdAContentDose"`
	UnitCbdAContentDoseUnitOfMeasureName *string `json:"UnitCbdAContentDoseUnitOfMeasureName"`
	UnitCbdAContentUnitOfMeasureName *string `json:"UnitCbdAContentUnitOfMeasureName"`
	UnitCbdAPercent *float64 `json:"UnitCbdAPercent"`
	UnitCbdContent *float64 `json:"UnitCbdContent"`
	UnitCbdContentDose *float64 `json:"UnitCbdContentDose"`
	UnitCbdContentDoseUnitOfMeasureName *string `json:"UnitCbdContentDoseUnitOfMeasureName"`
	UnitCbdContentUnitOfMeasureName *string `json:"UnitCbdContentUnitOfMeasureName"`
	UnitCbdPercent *float64 `json:"UnitCbdPercent"`
	UnitOfMeasureName *string `json:"UnitOfMeasureName"`
	UnitQuantity *string `json:"UnitQuantity"`
	UnitQuantityUnitOfMeasureName *string `json:"UnitQuantityUnitOfMeasureName"`
	UnitThcAContent *float64 `json:"UnitThcAContent"`
	UnitThcAContentDose *float64 `json:"UnitThcAContentDose"`
	UnitThcAContentDoseUnitOfMeasureId *int `json:"UnitThcAContentDoseUnitOfMeasureId"`
	UnitThcAContentDoseUnitOfMeasureName *string `json:"UnitThcAContentDoseUnitOfMeasureName"`
	UnitThcAContentUnitOfMeasureName *string `json:"UnitThcAContentUnitOfMeasureName"`
	UnitThcAPercent *float64 `json:"UnitThcAPercent"`
	UnitThcContent *float64 `json:"UnitThcContent"`
	UnitThcContentDose *float64 `json:"UnitThcContentDose"`
	UnitThcContentDoseUnitOfMeasureId *int `json:"UnitThcContentDoseUnitOfMeasureId"`
	UnitThcContentDoseUnitOfMeasureName *string `json:"UnitThcContentDoseUnitOfMeasureName"`
	UnitThcContentUnitOfMeasureName *string `json:"UnitThcContentUnitOfMeasureName"`
	UnitThcPercent *float64 `json:"UnitThcPercent"`
	UnitVolume *float64 `json:"UnitVolume"`
	UnitVolumeUnitOfMeasureName *string `json:"UnitVolumeUnitOfMeasureName"`
	UnitWeight *float64 `json:"UnitWeight"`
	UnitWeightUnitOfMeasureName *string `json:"UnitWeightUnitOfMeasureName"`
}

type PlantDataProductLabel struct {
	IsActive bool `json:"IsActive"`
	IsChildFromParentWithLabel bool `json:"IsChildFromParentWithLabel"`
	IsDiscontinued bool `json:"IsDiscontinued"`
	LastLabelGenerationDate *string `json:"LastLabelGenerationDate"`
	PackageId int `json:"PackageId"`
	QrCount int `json:"QrCount"`
	TagId *int `json:"TagId"`
}

