package models

type Sale struct {
	Ids []float64 `json:"Ids"`
	Warnings *string `json:"Warnings"`
	Id int `json:"Id"`
	Name string `json:"Name"`
	CurrentPage int `json:"CurrentPage"`
	Data []SaleData `json:"Data"`
	Page int `json:"Page"`
	PageSize int `json:"PageSize"`
	RecordsOnPage int `json:"RecordsOnPage"`
	Total int `json:"Total"`
	TotalPages int `json:"TotalPages"`
	TotalRecords int `json:"TotalRecords"`
	AcceptedDateTime *string `json:"AcceptedDateTime"`
	ActualArrivalDateTime *string `json:"ActualArrivalDateTime"`
	ActualDepartureDateTime *string `json:"ActualDepartureDateTime"`
	ActualReturnArrivalDateTime *string `json:"ActualReturnArrivalDateTime"`
	ActualReturnDepartureDateTime *string `json:"ActualReturnDepartureDateTime"`
	CompletedDateTime *string `json:"CompletedDateTime"`
	ConsumerId string `json:"ConsumerId"`
	DeliveryNumber *string `json:"DeliveryNumber"`
	Direction string `json:"Direction"`
	DriverEmployeeId string `json:"DriverEmployeeId"`
	DriverName string `json:"DriverName"`
	DriversLicenseNumber string `json:"DriversLicenseNumber"`
	EstimatedArrivalDateTime string `json:"EstimatedArrivalDateTime"`
	EstimatedDepartureDateTime string `json:"EstimatedDepartureDateTime"`
	EstimatedReturnArrivalDateTime *string `json:"EstimatedReturnArrivalDateTime"`
	EstimatedReturnDepartureDateTime *string `json:"EstimatedReturnDepartureDateTime"`
	FacilityLicenseNumber *string `json:"FacilityLicenseNumber"`
	FacilityName *string `json:"FacilityName"`
	LastModified string `json:"LastModified"`
	PatientLicenseNumber *string `json:"PatientLicenseNumber"`
	PlannedRoute string `json:"PlannedRoute"`
	RecipientAddressCity string `json:"RecipientAddressCity"`
	RecipientAddressCounty *string `json:"RecipientAddressCounty"`
	RecipientAddressPostalCode string `json:"RecipientAddressPostalCode"`
	RecipientAddressState string `json:"RecipientAddressState"`
	RecipientAddressStreet1 string `json:"RecipientAddressStreet1"`
	RecipientAddressStreet2 string `json:"RecipientAddressStreet2"`
	RecipientDeliveryZoneId *int `json:"RecipientDeliveryZoneId"`
	RecipientDeliveryZoneName *string `json:"RecipientDeliveryZoneName"`
	RecipientName *string `json:"RecipientName"`
	RecipientZoneId *int `json:"RecipientZoneId"`
	RecordedByUserName *string `json:"RecordedByUserName"`
	RecordedDateTime string `json:"RecordedDateTime"`
	SalesCustomerType string `json:"SalesCustomerType"`
	SalesDateTime string `json:"SalesDateTime"`
	SalesDeliveryState string `json:"SalesDeliveryState"`
	ShipperFacilityLicenseNumber *string `json:"ShipperFacilityLicenseNumber"`
	TotalPackages int `json:"TotalPackages"`
	TotalPrice int `json:"TotalPrice"`
	Transactions []interface{} `json:"Transactions"`
	TransporterFacilityId *int `json:"TransporterFacilityId"`
	TransporterFacilityLicenseNumber *string `json:"TransporterFacilityLicenseNumber"`
	TransporterFacilityName *string `json:"TransporterFacilityName"`
	VehicleLicensePlateNumber string `json:"VehicleLicensePlateNumber"`
	VehicleMake string `json:"VehicleMake"`
	VehicleModel string `json:"VehicleModel"`
	VoidedDate *string `json:"VoidedDate"`
	AllowFullEdit bool `json:"AllowFullEdit"`
	DateTime string `json:"DateTime"`
	Destinations []interface{} `json:"Destinations"`
	Leg int `json:"Leg"`
	Packages []interface{} `json:"Packages"`
	RestockDateTime *string `json:"RestockDateTime"`
	RetailerDeliveryNumber string `json:"RetailerDeliveryNumber"`
	RetailerDeliveryState string `json:"RetailerDeliveryState"`
	TotalPriceSold int `json:"TotalPriceSold"`
	VehicleInfo string `json:"VehicleInfo"`
	RequiresImmatureWasteWeight bool `json:"RequiresImmatureWasteWeight"`
	RequiresMatureWasteWeight bool `json:"RequiresMatureWasteWeight"`
	RequiresNote bool `json:"RequiresNote"`
	RequiresWasteWeight bool `json:"RequiresWasteWeight"`
	ArchivedDate *string `json:"ArchivedDate"`
	CaregiverLicenseNumber *string `json:"CaregiverLicenseNumber"`
	ExternalReceiptNumber string `json:"ExternalReceiptNumber"`
	IdentificationMethod *string `json:"IdentificationMethod"`
	IsFinal bool `json:"IsFinal"`
	PatientRegistrationLocationId *int `json:"PatientRegistrationLocationId"`
	ReceiptNumber *string `json:"ReceiptNumber"`
	SalesDate string `json:"SalesDate"`
	TotalTransactions int `json:"TotalTransactions"`
	CityTax *string `json:"CityTax"`
	CountyTax *string `json:"CountyTax"`
	DiscountAmount *string `json:"DiscountAmount"`
	ExciseTax *string `json:"ExciseTax"`
	InvoiceNumber *string `json:"InvoiceNumber"`
	ItemServingSize *string `json:"ItemServingSize"`
	ItemStrainName *string `json:"ItemStrainName"`
	ItemSupplyDurationDays *int `json:"ItemSupplyDurationDays"`
	ItemUnitCbdAContent *float64 `json:"ItemUnitCbdAContent"`
	ItemUnitCbdAContentDose *float64 `json:"ItemUnitCbdAContentDose"`
	ItemUnitCbdAContentDoseUnitOfMeasureName *string `json:"ItemUnitCbdAContentDoseUnitOfMeasureName"`
	ItemUnitCbdAContentUnitOfMeasureName *string `json:"ItemUnitCbdAContentUnitOfMeasureName"`
	ItemUnitCbdAPercent *float64 `json:"ItemUnitCbdAPercent"`
	ItemUnitCbdContent *float64 `json:"ItemUnitCbdContent"`
	ItemUnitCbdContentDose *float64 `json:"ItemUnitCbdContentDose"`
	ItemUnitCbdContentDoseUnitOfMeasureName *string `json:"ItemUnitCbdContentDoseUnitOfMeasureName"`
	ItemUnitCbdContentUnitOfMeasureName *string `json:"ItemUnitCbdContentUnitOfMeasureName"`
	ItemUnitCbdPercent *float64 `json:"ItemUnitCbdPercent"`
	ItemUnitQuantity *string `json:"ItemUnitQuantity"`
	ItemUnitQuantityUnitOfMeasureName *string `json:"ItemUnitQuantityUnitOfMeasureName"`
	ItemUnitThcAContent *float64 `json:"ItemUnitThcAContent"`
	ItemUnitThcAContentDose *float64 `json:"ItemUnitThcAContentDose"`
	ItemUnitThcAContentDoseUnitOfMeasureName *string `json:"ItemUnitThcAContentDoseUnitOfMeasureName"`
	ItemUnitThcAContentUnitOfMeasureName *string `json:"ItemUnitThcAContentUnitOfMeasureName"`
	ItemUnitThcAPercent *float64 `json:"ItemUnitThcAPercent"`
	ItemUnitThcContent *float64 `json:"ItemUnitThcContent"`
	ItemUnitThcContentDose *float64 `json:"ItemUnitThcContentDose"`
	ItemUnitThcContentDoseUnitOfMeasureName *string `json:"ItemUnitThcContentDoseUnitOfMeasureName"`
	ItemUnitThcContentUnitOfMeasureName *string `json:"ItemUnitThcContentUnitOfMeasureName"`
	ItemUnitThcPercent *float64 `json:"ItemUnitThcPercent"`
	ItemUnitVolume *float64 `json:"ItemUnitVolume"`
	ItemUnitVolumeUnitOfMeasureName *string `json:"ItemUnitVolumeUnitOfMeasureName"`
	ItemUnitWeight *float64 `json:"ItemUnitWeight"`
	ItemUnitWeightUnitOfMeasureName *string `json:"ItemUnitWeightUnitOfMeasureName"`
	MunicipalTax *string `json:"MunicipalTax"`
	PackageId int `json:"PackageId"`
	PackageLabel string `json:"PackageLabel"`
	Price *string `json:"Price"`
	ProductCategoryName *string `json:"ProductCategoryName"`
	ProductName string `json:"ProductName"`
	QrCodeDocument *string `json:"QrCodeDocument"`
	QuantitySold int `json:"QuantitySold"`
	SalesTax *string `json:"SalesTax"`
	SubTotal *string `json:"SubTotal"`
	TripId *int `json:"TripId"`
	TripManifestNumber *string `json:"TripManifestNumber"`
	UnitOfMeasureAbbreviation string `json:"UnitOfMeasureAbbreviation"`
	UnitOfMeasureName string `json:"UnitOfMeasureName"`
	UnitThcContent *float64 `json:"UnitThcContent"`
	UnitThcPercent *float64 `json:"UnitThcPercent"`
	UnitWeight *float64 `json:"UnitWeight"`
}

type SaleData struct {
	Id int `json:"Id"`
	Name string `json:"Name"`
	AcceptedDateTime *string `json:"AcceptedDateTime"`
	ActualArrivalDateTime *string `json:"ActualArrivalDateTime"`
	ActualDepartureDateTime *string `json:"ActualDepartureDateTime"`
	ActualReturnArrivalDateTime *string `json:"ActualReturnArrivalDateTime"`
	ActualReturnDepartureDateTime *string `json:"ActualReturnDepartureDateTime"`
	CompletedDateTime *string `json:"CompletedDateTime"`
	ConsumerId string `json:"ConsumerId"`
	DeliveryNumber *string `json:"DeliveryNumber"`
	Direction string `json:"Direction"`
	DriverEmployeeId string `json:"DriverEmployeeId"`
	DriverName string `json:"DriverName"`
	DriversLicenseNumber string `json:"DriversLicenseNumber"`
	EstimatedArrivalDateTime string `json:"EstimatedArrivalDateTime"`
	EstimatedDepartureDateTime string `json:"EstimatedDepartureDateTime"`
	EstimatedReturnArrivalDateTime *string `json:"EstimatedReturnArrivalDateTime"`
	EstimatedReturnDepartureDateTime *string `json:"EstimatedReturnDepartureDateTime"`
	FacilityLicenseNumber *string `json:"FacilityLicenseNumber"`
	FacilityName *string `json:"FacilityName"`
	LastModified string `json:"LastModified"`
	PatientLicenseNumber *string `json:"PatientLicenseNumber"`
	PlannedRoute string `json:"PlannedRoute"`
	RecipientAddressCity string `json:"RecipientAddressCity"`
	RecipientAddressCounty *string `json:"RecipientAddressCounty"`
	RecipientAddressPostalCode string `json:"RecipientAddressPostalCode"`
	RecipientAddressState string `json:"RecipientAddressState"`
	RecipientAddressStreet1 string `json:"RecipientAddressStreet1"`
	RecipientAddressStreet2 string `json:"RecipientAddressStreet2"`
	RecipientDeliveryZoneId *int `json:"RecipientDeliveryZoneId"`
	RecipientDeliveryZoneName *string `json:"RecipientDeliveryZoneName"`
	RecipientName *string `json:"RecipientName"`
	RecipientZoneId *int `json:"RecipientZoneId"`
	RecordedByUserName *string `json:"RecordedByUserName"`
	RecordedDateTime string `json:"RecordedDateTime"`
	SalesCustomerType string `json:"SalesCustomerType"`
	SalesDateTime string `json:"SalesDateTime"`
	SalesDeliveryState string `json:"SalesDeliveryState"`
	ShipperFacilityLicenseNumber *string `json:"ShipperFacilityLicenseNumber"`
	TotalPackages int `json:"TotalPackages"`
	TotalPrice int `json:"TotalPrice"`
	Transactions []interface{} `json:"Transactions"`
	TransporterFacilityId *int `json:"TransporterFacilityId"`
	TransporterFacilityLicenseNumber *string `json:"TransporterFacilityLicenseNumber"`
	TransporterFacilityName *string `json:"TransporterFacilityName"`
	VehicleLicensePlateNumber string `json:"VehicleLicensePlateNumber"`
	VehicleMake string `json:"VehicleMake"`
	VehicleModel string `json:"VehicleModel"`
	VoidedDate *string `json:"VoidedDate"`
	AllowFullEdit bool `json:"AllowFullEdit"`
	DateTime string `json:"DateTime"`
	Destinations []interface{} `json:"Destinations"`
	Leg int `json:"Leg"`
	Packages []interface{} `json:"Packages"`
	RestockDateTime *string `json:"RestockDateTime"`
	RetailerDeliveryNumber string `json:"RetailerDeliveryNumber"`
	RetailerDeliveryState string `json:"RetailerDeliveryState"`
	TotalPriceSold int `json:"TotalPriceSold"`
	VehicleInfo string `json:"VehicleInfo"`
	RequiresImmatureWasteWeight bool `json:"RequiresImmatureWasteWeight"`
	RequiresMatureWasteWeight bool `json:"RequiresMatureWasteWeight"`
	RequiresNote bool `json:"RequiresNote"`
	RequiresWasteWeight bool `json:"RequiresWasteWeight"`
	ArchivedDate *string `json:"ArchivedDate"`
	CaregiverLicenseNumber *string `json:"CaregiverLicenseNumber"`
	ExternalReceiptNumber string `json:"ExternalReceiptNumber"`
	IdentificationMethod *string `json:"IdentificationMethod"`
	IsFinal bool `json:"IsFinal"`
	PatientRegistrationLocationId *int `json:"PatientRegistrationLocationId"`
	ReceiptNumber *string `json:"ReceiptNumber"`
}

type SaleDestination struct {
	AcceptedDateTime *string `json:"AcceptedDateTime"`
	ActualArrivalDateTime *string `json:"ActualArrivalDateTime"`
	ActualDepartureDateTime *string `json:"ActualDepartureDateTime"`
	ActualReturnArrivalDateTime *string `json:"ActualReturnArrivalDateTime"`
	ActualReturnDepartureDateTime *string `json:"ActualReturnDepartureDateTime"`
	CompletedDateTime *string `json:"CompletedDateTime"`
	ConsumerId string `json:"ConsumerId"`
	DeliveryNumber *string `json:"DeliveryNumber"`
	Direction string `json:"Direction"`
	DriverEmployeeId string `json:"DriverEmployeeId"`
	DriverName string `json:"DriverName"`
	DriversLicenseNumber string `json:"DriversLicenseNumber"`
	EstimatedArrivalDateTime string `json:"EstimatedArrivalDateTime"`
	EstimatedDepartureDateTime string `json:"EstimatedDepartureDateTime"`
	EstimatedReturnArrivalDateTime *string `json:"EstimatedReturnArrivalDateTime"`
	EstimatedReturnDepartureDateTime *string `json:"EstimatedReturnDepartureDateTime"`
	FacilityLicenseNumber *string `json:"FacilityLicenseNumber"`
	FacilityName *string `json:"FacilityName"`
	Id int `json:"Id"`
	LastModified string `json:"LastModified"`
	PatientLicenseNumber *string `json:"PatientLicenseNumber"`
	PlannedRoute string `json:"PlannedRoute"`
	RecipientAddressCity string `json:"RecipientAddressCity"`
	RecipientAddressCounty *string `json:"RecipientAddressCounty"`
	RecipientAddressPostalCode string `json:"RecipientAddressPostalCode"`
	RecipientAddressState string `json:"RecipientAddressState"`
	RecipientAddressStreet1 string `json:"RecipientAddressStreet1"`
	RecipientAddressStreet2 string `json:"RecipientAddressStreet2"`
	RecipientDeliveryZoneId *int `json:"RecipientDeliveryZoneId"`
	RecipientDeliveryZoneName *string `json:"RecipientDeliveryZoneName"`
	RecipientName *string `json:"RecipientName"`
	RecipientZoneId *int `json:"RecipientZoneId"`
	RecordedByUserName *string `json:"RecordedByUserName"`
	RecordedDateTime string `json:"RecordedDateTime"`
	SalesCustomerType string `json:"SalesCustomerType"`
	SalesDateTime string `json:"SalesDateTime"`
	SalesDeliveryState string `json:"SalesDeliveryState"`
	ShipperFacilityLicenseNumber *string `json:"ShipperFacilityLicenseNumber"`
	TotalPackages int `json:"TotalPackages"`
	TotalPrice int `json:"TotalPrice"`
	Transactions []interface{} `json:"Transactions"`
	TransporterFacilityId *int `json:"TransporterFacilityId"`
	TransporterFacilityLicenseNumber *string `json:"TransporterFacilityLicenseNumber"`
	TransporterFacilityName *string `json:"TransporterFacilityName"`
	VehicleLicensePlateNumber string `json:"VehicleLicensePlateNumber"`
	VehicleMake string `json:"VehicleMake"`
	VehicleModel string `json:"VehicleModel"`
	VoidedDate *string `json:"VoidedDate"`
}

type SalePackage struct {
	ArchivedDate *string `json:"ArchivedDate"`
	CompletedDateTime *string `json:"CompletedDateTime"`
	IsOnInvestigationHold bool `json:"IsOnInvestigationHold"`
	IsOnInvestigationRecall bool `json:"IsOnInvestigationRecall"`
	IsOnRecall *bool `json:"IsOnRecall"`
	IsOnRecallCombined bool `json:"IsOnRecallCombined"`
	ItemServingSize *string `json:"ItemServingSize"`
	ItemStrainName *string `json:"ItemStrainName"`
	ItemSupplyDurationDays *int `json:"ItemSupplyDurationDays"`
	ItemUnitCbdContent *float64 `json:"ItemUnitCbdContent"`
	ItemUnitCbdContentDose *float64 `json:"ItemUnitCbdContentDose"`
	ItemUnitCbdContentDoseUnitOfMeasureName *string `json:"ItemUnitCbdContentDoseUnitOfMeasureName"`
	ItemUnitCbdContentUnitOfMeasureName *string `json:"ItemUnitCbdContentUnitOfMeasureName"`
	ItemUnitCbdPercent *float64 `json:"ItemUnitCbdPercent"`
	ItemUnitQuantity *string `json:"ItemUnitQuantity"`
	ItemUnitQuantityUnitOfMeasureName *string `json:"ItemUnitQuantityUnitOfMeasureName"`
	ItemUnitThcContent *float64 `json:"ItemUnitThcContent"`
	ItemUnitThcContentDose *float64 `json:"ItemUnitThcContentDose"`
	ItemUnitThcContentDoseUnitOfMeasureName *string `json:"ItemUnitThcContentDoseUnitOfMeasureName"`
	ItemUnitThcContentUnitOfMeasureName *string `json:"ItemUnitThcContentUnitOfMeasureName"`
	ItemUnitThcPercent *float64 `json:"ItemUnitThcPercent"`
	ItemUnitVolume *float64 `json:"ItemUnitVolume"`
	ItemUnitVolumeUnitOfMeasureName *string `json:"ItemUnitVolumeUnitOfMeasureName"`
	ItemUnitWeight *float64 `json:"ItemUnitWeight"`
	ItemUnitWeightUnitOfMeasureName *string `json:"ItemUnitWeightUnitOfMeasureName"`
	LastModified string `json:"LastModified"`
	PackageId int `json:"PackageId"`
	PackageLabel string `json:"PackageLabel"`
	ProductCategoryName *string `json:"ProductCategoryName"`
	ProductName *string `json:"ProductName"`
	Quantity int `json:"Quantity"`
	RecordedByUserName *string `json:"RecordedByUserName"`
	RecordedDateTime string `json:"RecordedDateTime"`
	RetailerDeliveryState *string `json:"RetailerDeliveryState"`
	TotalPrice float64 `json:"TotalPrice"`
	UnitOfMeasureAbbreviation *string `json:"UnitOfMeasureAbbreviation"`
	UnitOfMeasureName string `json:"UnitOfMeasureName"`
}

