package models

type Transfer struct {
	Ids []float64 `json:"Ids"`
	Warnings *string `json:"Warnings"`
	ActualArrivalDateTime *string `json:"ActualArrivalDateTime"`
	ActualDepartureDateTime *string `json:"ActualDepartureDateTime"`
	ActualReturnArrivalDateTime *string `json:"ActualReturnArrivalDateTime"`
	ActualReturnDepartureDateTime *string `json:"ActualReturnDepartureDateTime"`
	DeliveryNumber int `json:"DeliveryNumber"`
	DeliveryPackageCount int `json:"DeliveryPackageCount"`
	DeliveryReceivedPackageCount int `json:"DeliveryReceivedPackageCount"`
	EstimatedArrivalDateTime string `json:"EstimatedArrivalDateTime"`
	EstimatedDepartureDateTime string `json:"EstimatedDepartureDateTime"`
	EstimatedReturnArrivalDateTime *string `json:"EstimatedReturnArrivalDateTime"`
	EstimatedReturnDepartureDateTime *string `json:"EstimatedReturnDepartureDateTime"`
	GrossUnitOfWeightId *int `json:"GrossUnitOfWeightId"`
	GrossUnitOfWeightName *string `json:"GrossUnitOfWeightName"`
	GrossWeight *float64 `json:"GrossWeight"`
	Id int `json:"Id"`
	InvoiceNumber *string `json:"InvoiceNumber"`
	ManifestNumber *string `json:"ManifestNumber"`
	PDFDocumentFileSystemId *int `json:"PDFDocumentFileSystemId"`
	PlannedRoute string `json:"PlannedRoute"`
	ReceivedDateTime string `json:"ReceivedDateTime"`
	RecipientFacilityLicenseNumber string `json:"RecipientFacilityLicenseNumber"`
	RecipientFacilityName string `json:"RecipientFacilityName"`
	RejectedPackagesReturned bool `json:"RejectedPackagesReturned"`
	ShipmentTransactionType string `json:"ShipmentTransactionType"`
	ShipmentTypeName string `json:"ShipmentTypeName"`
	CurrentPage int `json:"CurrentPage"`
	Data []TransferData `json:"Data"`
	Page int `json:"Page"`
	PageSize int `json:"PageSize"`
	RecordsOnPage int `json:"RecordsOnPage"`
	Total int `json:"Total"`
	TotalPages int `json:"TotalPages"`
	TotalRecords int `json:"TotalRecords"`
	ContainsRemediatedProduct bool `json:"ContainsRemediatedProduct"`
	ExpirationDate *string `json:"ExpirationDate"`
	ExternalId *int `json:"ExternalId"`
	IsDonation bool `json:"IsDonation"`
	IsTestingSample bool `json:"IsTestingSample"`
	IsTradeSample bool `json:"IsTradeSample"`
	IsTradeSamplePersistent bool `json:"IsTradeSamplePersistent"`
	ItemBrandName *string `json:"ItemBrandName"`
	ItemCategoryName string `json:"ItemCategoryName"`
	ItemId int `json:"ItemId"`
	ItemName string `json:"ItemName"`
	ItemServingSize *string `json:"ItemServingSize"`
	ItemStrainName *string `json:"ItemStrainName"`
	ItemSupplyDurationDays *int `json:"ItemSupplyDurationDays"`
	ItemUnitCbdAContent *float64 `json:"ItemUnitCbdAContent"`
	ItemUnitCbdAContentDose *float64 `json:"ItemUnitCbdAContentDose"`
	ItemUnitCbdAContentDoseUnitOfMeasureName *string `json:"ItemUnitCbdAContentDoseUnitOfMeasureName"`
	ItemUnitCbdAContentUnitOfMeasureName *string `json:"ItemUnitCbdAContentUnitOfMeasureName"`
	ItemUnitCbdAPercent *float64 `json:"ItemUnitCbdAPercent"`
	ItemUnitCbdContent *float64 `json:"ItemUnitCbdContent"`
	ItemUnitCbdContentDose *float64 `json:"ItemUnitCbdContentDose"`
	ItemUnitCbdContentDoseUnitOfMeasureName *string `json:"ItemUnitCbdContentDoseUnitOfMeasureName"`
	ItemUnitCbdContentUnitOfMeasureName *string `json:"ItemUnitCbdContentUnitOfMeasureName"`
	ItemUnitCbdPercent *float64 `json:"ItemUnitCbdPercent"`
	ItemUnitQuantity *string `json:"ItemUnitQuantity"`
	ItemUnitQuantityUnitOfMeasureName *string `json:"ItemUnitQuantityUnitOfMeasureName"`
	ItemUnitThcAContent *float64 `json:"ItemUnitThcAContent"`
	ItemUnitThcAContentDose *float64 `json:"ItemUnitThcAContentDose"`
	ItemUnitThcAContentDoseUnitOfMeasureName *string `json:"ItemUnitThcAContentDoseUnitOfMeasureName"`
	ItemUnitThcAContentUnitOfMeasureName *string `json:"ItemUnitThcAContentUnitOfMeasureName"`
	ItemUnitThcAPercent *float64 `json:"ItemUnitThcAPercent"`
	ItemUnitThcContent *float64 `json:"ItemUnitThcContent"`
	ItemUnitThcContentDose *float64 `json:"ItemUnitThcContentDose"`
	ItemUnitThcContentDoseUnitOfMeasureName *string `json:"ItemUnitThcContentDoseUnitOfMeasureName"`
	ItemUnitThcContentUnitOfMeasureName *string `json:"ItemUnitThcContentUnitOfMeasureName"`
	ItemUnitThcPercent *float64 `json:"ItemUnitThcPercent"`
	ItemUnitVolume *float64 `json:"ItemUnitVolume"`
	ItemUnitVolumeUnitOfMeasureName *string `json:"ItemUnitVolumeUnitOfMeasureName"`
	ItemUnitWeight *float64 `json:"ItemUnitWeight"`
	ItemUnitWeightUnitOfMeasureName *string `json:"ItemUnitWeightUnitOfMeasureName"`
	LabTestingState string `json:"LabTestingState"`
	PackageId int `json:"PackageId"`
	PackageLabel string `json:"PackageLabel"`
	PackageType string `json:"PackageType"`
	PackagedDate *string `json:"PackagedDate"`
	ProductCategoryName string `json:"ProductCategoryName"`
	ProductLabel TransferProductLabel `json:"ProductLabel"`
	ProductName string `json:"ProductName"`
	ProductRequiresRemediation bool `json:"ProductRequiresRemediation"`
	ProductionBatchNumber *string `json:"ProductionBatchNumber"`
	ReceivedQuantity int `json:"ReceivedQuantity"`
	ReceivedUnitOfMeasureName string `json:"ReceivedUnitOfMeasureName"`
	RemediationDate *string `json:"RemediationDate"`
	SellByDate *string `json:"SellByDate"`
	ShipmentPackageState string `json:"ShipmentPackageState"`
	ShippedQuantity int `json:"ShippedQuantity"`
	ShippedUnitOfMeasureName string `json:"ShippedUnitOfMeasureName"`
	SourceHarvestNames *string `json:"SourceHarvestNames"`
	SourcePackageIsDonation bool `json:"SourcePackageIsDonation"`
	SourcePackageIsTradeSample bool `json:"SourcePackageIsTradeSample"`
	SourcePackageLabels *string `json:"SourcePackageLabels"`
	SourceProductionBatchNumbers *string `json:"SourceProductionBatchNumbers"`
	UseByDate *string `json:"UseByDate"`
	LabTestBatchId int `json:"LabTestBatchId"`
	LabTestBatchName string `json:"LabTestBatchName"`
	ReceiverWholesalePrice *string `json:"ReceiverWholesalePrice"`
	ShipperWholesalePrice *string `json:"ShipperWholesalePrice"`
	TransporterDirection string `json:"TransporterDirection"`
	TransporterFacilityLicenseNumber string `json:"TransporterFacilityLicenseNumber"`
	TransporterFacilityName string `json:"TransporterFacilityName"`
	ActualDriverStartDateTime *string `json:"ActualDriverStartDateTime"`
	DriverLayoverLeg *string `json:"DriverLayoverLeg"`
	DriverName string `json:"DriverName"`
	DriverOccupationalLicenseNumber string `json:"DriverOccupationalLicenseNumber"`
	DriverVehicleLicenseNumber string `json:"DriverVehicleLicenseNumber"`
	VehicleLicensePlateNumber string `json:"VehicleLicensePlateNumber"`
	VehicleMake string `json:"VehicleMake"`
	VehicleModel string `json:"VehicleModel"`
	ContainsDonation bool `json:"ContainsDonation"`
	ContainsPlantPackage bool `json:"ContainsPlantPackage"`
	ContainsProductPackage bool `json:"ContainsProductPackage"`
	ContainsProductRequiresRemediation bool `json:"ContainsProductRequiresRemediation"`
	ContainsRemediatedProductPackage bool `json:"ContainsRemediatedProductPackage"`
	ContainsTestingSample bool `json:"ContainsTestingSample"`
	ContainsTradeSample bool `json:"ContainsTradeSample"`
	CreatedByUserName *string `json:"CreatedByUserName"`
	CreatedDateTime string `json:"CreatedDateTime"`
	DeliveryCount int `json:"DeliveryCount"`
	DeliveryId int `json:"DeliveryId"`
	IsVoided bool `json:"IsVoided"`
	LastModified string `json:"LastModified"`
	Name *string `json:"Name"`
	OriginatingTemplateId *int `json:"OriginatingTemplateId"`
	PackageCount int `json:"PackageCount"`
	ReceivedDeliveryCount int `json:"ReceivedDeliveryCount"`
	ReceivedPackageCount int `json:"ReceivedPackageCount"`
	ShipmentLicenseType int `json:"ShipmentLicenseType"`
	ShipperFacilityLicenseNumber string `json:"ShipperFacilityLicenseNumber"`
	ShipperFacilityName string `json:"ShipperFacilityName"`
	BypassApproval bool `json:"BypassApproval"`
	ExternalIncomingCanRecordExternalIdentifier bool `json:"ExternalIncomingCanRecordExternalIdentifier"`
	ExternalIncomingExternalIdentifierRequired bool `json:"ExternalIncomingExternalIdentifierRequired"`
	ExternalOutgoingCanRecordExternalIdentifier bool `json:"ExternalOutgoingCanRecordExternalIdentifier"`
	ExternalOutgoingExternalIdentifierRequired bool `json:"ExternalOutgoingExternalIdentifierRequired"`
	ForExternalIncomingShipments bool `json:"ForExternalIncomingShipments"`
	ForExternalOutgoingShipments bool `json:"ForExternalOutgoingShipments"`
	ForLicensedShipments bool `json:"ForLicensedShipments"`
	RequiresDestinationGrossWeight bool `json:"RequiresDestinationGrossWeight"`
	RequiresInvoiceNumber bool `json:"RequiresInvoiceNumber"`
	RequiresPDFDocument bool `json:"RequiresPDFDocument"`
	RequiresPackagesGrossWeight bool `json:"RequiresPackagesGrossWeight"`
	TransactionType string `json:"TransactionType"`
}

type TransferData struct {
	ActualArrivalDateTime *string `json:"ActualArrivalDateTime"`
	ActualDepartureDateTime *string `json:"ActualDepartureDateTime"`
	ActualReturnArrivalDateTime *string `json:"ActualReturnArrivalDateTime"`
	ActualReturnDepartureDateTime *string `json:"ActualReturnDepartureDateTime"`
	DeliveryNumber int `json:"DeliveryNumber"`
	DeliveryPackageCount int `json:"DeliveryPackageCount"`
	DeliveryReceivedPackageCount int `json:"DeliveryReceivedPackageCount"`
	EstimatedArrivalDateTime string `json:"EstimatedArrivalDateTime"`
	EstimatedDepartureDateTime string `json:"EstimatedDepartureDateTime"`
	EstimatedReturnArrivalDateTime *string `json:"EstimatedReturnArrivalDateTime"`
	EstimatedReturnDepartureDateTime *string `json:"EstimatedReturnDepartureDateTime"`
	GrossUnitOfWeightId *int `json:"GrossUnitOfWeightId"`
	GrossUnitOfWeightName *string `json:"GrossUnitOfWeightName"`
	GrossWeight *float64 `json:"GrossWeight"`
	Id int `json:"Id"`
	InvoiceNumber *string `json:"InvoiceNumber"`
	ManifestNumber *string `json:"ManifestNumber"`
	PDFDocumentFileSystemId *int `json:"PDFDocumentFileSystemId"`
	PlannedRoute string `json:"PlannedRoute"`
	ReceivedDateTime string `json:"ReceivedDateTime"`
	RecipientFacilityLicenseNumber string `json:"RecipientFacilityLicenseNumber"`
	RecipientFacilityName string `json:"RecipientFacilityName"`
	RejectedPackagesReturned bool `json:"RejectedPackagesReturned"`
	ShipmentTransactionType string `json:"ShipmentTransactionType"`
	ShipmentTypeName string `json:"ShipmentTypeName"`
	ContainsRemediatedProduct bool `json:"ContainsRemediatedProduct"`
	ExpirationDate *string `json:"ExpirationDate"`
	ExternalId *int `json:"ExternalId"`
	IsDonation bool `json:"IsDonation"`
	IsTestingSample bool `json:"IsTestingSample"`
	IsTradeSample bool `json:"IsTradeSample"`
	IsTradeSamplePersistent bool `json:"IsTradeSamplePersistent"`
	ItemBrandName *string `json:"ItemBrandName"`
	ItemCategoryName string `json:"ItemCategoryName"`
	ItemId int `json:"ItemId"`
	ItemName string `json:"ItemName"`
	ItemServingSize *string `json:"ItemServingSize"`
	ItemStrainName *string `json:"ItemStrainName"`
	ItemSupplyDurationDays *int `json:"ItemSupplyDurationDays"`
	ItemUnitCbdAContent *float64 `json:"ItemUnitCbdAContent"`
	ItemUnitCbdAContentDose *float64 `json:"ItemUnitCbdAContentDose"`
	ItemUnitCbdAContentDoseUnitOfMeasureName *string `json:"ItemUnitCbdAContentDoseUnitOfMeasureName"`
	ItemUnitCbdAContentUnitOfMeasureName *string `json:"ItemUnitCbdAContentUnitOfMeasureName"`
	ItemUnitCbdAPercent *float64 `json:"ItemUnitCbdAPercent"`
	ItemUnitCbdContent *float64 `json:"ItemUnitCbdContent"`
	ItemUnitCbdContentDose *float64 `json:"ItemUnitCbdContentDose"`
	ItemUnitCbdContentDoseUnitOfMeasureName *string `json:"ItemUnitCbdContentDoseUnitOfMeasureName"`
	ItemUnitCbdContentUnitOfMeasureName *string `json:"ItemUnitCbdContentUnitOfMeasureName"`
	ItemUnitCbdPercent *float64 `json:"ItemUnitCbdPercent"`
	ItemUnitQuantity *string `json:"ItemUnitQuantity"`
	ItemUnitQuantityUnitOfMeasureName *string `json:"ItemUnitQuantityUnitOfMeasureName"`
	ItemUnitThcAContent *float64 `json:"ItemUnitThcAContent"`
	ItemUnitThcAContentDose *float64 `json:"ItemUnitThcAContentDose"`
	ItemUnitThcAContentDoseUnitOfMeasureName *string `json:"ItemUnitThcAContentDoseUnitOfMeasureName"`
	ItemUnitThcAContentUnitOfMeasureName *string `json:"ItemUnitThcAContentUnitOfMeasureName"`
	ItemUnitThcAPercent *float64 `json:"ItemUnitThcAPercent"`
	ItemUnitThcContent *float64 `json:"ItemUnitThcContent"`
	ItemUnitThcContentDose *float64 `json:"ItemUnitThcContentDose"`
	ItemUnitThcContentDoseUnitOfMeasureName *string `json:"ItemUnitThcContentDoseUnitOfMeasureName"`
	ItemUnitThcContentUnitOfMeasureName *string `json:"ItemUnitThcContentUnitOfMeasureName"`
	ItemUnitThcPercent *float64 `json:"ItemUnitThcPercent"`
	ItemUnitVolume *float64 `json:"ItemUnitVolume"`
	ItemUnitVolumeUnitOfMeasureName *string `json:"ItemUnitVolumeUnitOfMeasureName"`
	ItemUnitWeight *float64 `json:"ItemUnitWeight"`
	ItemUnitWeightUnitOfMeasureName *string `json:"ItemUnitWeightUnitOfMeasureName"`
	LabTestingState string `json:"LabTestingState"`
	PackageId int `json:"PackageId"`
	PackageLabel string `json:"PackageLabel"`
	PackageType string `json:"PackageType"`
	PackagedDate *string `json:"PackagedDate"`
	ProductLabel TransferDataProductLabel `json:"ProductLabel"`
	ProductRequiresRemediation bool `json:"ProductRequiresRemediation"`
	ProductionBatchNumber *string `json:"ProductionBatchNumber"`
	ReceivedQuantity int `json:"ReceivedQuantity"`
	ReceivedUnitOfMeasureName string `json:"ReceivedUnitOfMeasureName"`
	RemediationDate *string `json:"RemediationDate"`
	SellByDate *string `json:"SellByDate"`
	ShipmentPackageState string `json:"ShipmentPackageState"`
	ShippedQuantity int `json:"ShippedQuantity"`
	ShippedUnitOfMeasureName string `json:"ShippedUnitOfMeasureName"`
	SourceHarvestNames *string `json:"SourceHarvestNames"`
	SourcePackageIsDonation bool `json:"SourcePackageIsDonation"`
	SourcePackageIsTradeSample bool `json:"SourcePackageIsTradeSample"`
	SourcePackageLabels *string `json:"SourcePackageLabels"`
	SourceProductionBatchNumbers *string `json:"SourceProductionBatchNumbers"`
	UseByDate *string `json:"UseByDate"`
	LabTestBatchId int `json:"LabTestBatchId"`
	LabTestBatchName string `json:"LabTestBatchName"`
	ReceiverWholesalePrice *string `json:"ReceiverWholesalePrice"`
	ShipperWholesalePrice *string `json:"ShipperWholesalePrice"`
	TransporterDirection string `json:"TransporterDirection"`
	TransporterFacilityLicenseNumber string `json:"TransporterFacilityLicenseNumber"`
	TransporterFacilityName string `json:"TransporterFacilityName"`
	ActualDriverStartDateTime *string `json:"ActualDriverStartDateTime"`
	DriverLayoverLeg *string `json:"DriverLayoverLeg"`
	DriverName string `json:"DriverName"`
	DriverOccupationalLicenseNumber string `json:"DriverOccupationalLicenseNumber"`
	DriverVehicleLicenseNumber string `json:"DriverVehicleLicenseNumber"`
	VehicleLicensePlateNumber string `json:"VehicleLicensePlateNumber"`
	VehicleMake string `json:"VehicleMake"`
	VehicleModel string `json:"VehicleModel"`
	CreatedByUserName *string `json:"CreatedByUserName"`
	CreatedDateTime string `json:"CreatedDateTime"`
	DeliveryCount int `json:"DeliveryCount"`
	DeliveryId int `json:"DeliveryId"`
	IsLayover bool `json:"IsLayover"`
	IsVoided bool `json:"IsVoided"`
	LastModified string `json:"LastModified"`
	PackageCount int `json:"PackageCount"`
	ReceivedDeliveryCount int `json:"ReceivedDeliveryCount"`
	ReceivedPackageCount int `json:"ReceivedPackageCount"`
	ShipperFacilityLicenseNumber string `json:"ShipperFacilityLicenseNumber"`
	ShipperFacilityName string `json:"ShipperFacilityName"`
	TransporterAcceptedDateTime *string `json:"TransporterAcceptedDateTime"`
	TransporterActualArrivalDateTime *string `json:"TransporterActualArrivalDateTime"`
	TransporterActualDepartureDateTime *string `json:"TransporterActualDepartureDateTime"`
	TransporterEstimatedArrivalDateTime *string `json:"TransporterEstimatedArrivalDateTime"`
	TransporterEstimatedDepartureDateTime *string `json:"TransporterEstimatedDepartureDateTime"`
	ContainsDonation bool `json:"ContainsDonation"`
	ContainsPlantPackage bool `json:"ContainsPlantPackage"`
	ContainsProductPackage bool `json:"ContainsProductPackage"`
	ContainsProductRequiresRemediation bool `json:"ContainsProductRequiresRemediation"`
	ContainsRemediatedProductPackage bool `json:"ContainsRemediatedProductPackage"`
	ContainsTestingSample bool `json:"ContainsTestingSample"`
	ContainsTradeSample bool `json:"ContainsTradeSample"`
	Name *string `json:"Name"`
	OriginatingTemplateId *int `json:"OriginatingTemplateId"`
	ShipmentLicenseType int `json:"ShipmentLicenseType"`
	BypassApproval bool `json:"BypassApproval"`
	ExternalIncomingCanRecordExternalIdentifier bool `json:"ExternalIncomingCanRecordExternalIdentifier"`
	ExternalIncomingExternalIdentifierRequired bool `json:"ExternalIncomingExternalIdentifierRequired"`
	ExternalOutgoingCanRecordExternalIdentifier bool `json:"ExternalOutgoingCanRecordExternalIdentifier"`
	ExternalOutgoingExternalIdentifierRequired bool `json:"ExternalOutgoingExternalIdentifierRequired"`
	ForExternalIncomingShipments bool `json:"ForExternalIncomingShipments"`
	ForExternalOutgoingShipments bool `json:"ForExternalOutgoingShipments"`
	ForLicensedShipments bool `json:"ForLicensedShipments"`
	RequiresDestinationGrossWeight bool `json:"RequiresDestinationGrossWeight"`
	RequiresInvoiceNumber bool `json:"RequiresInvoiceNumber"`
	RequiresPDFDocument bool `json:"RequiresPDFDocument"`
	RequiresPackagesGrossWeight bool `json:"RequiresPackagesGrossWeight"`
	TransactionType string `json:"TransactionType"`
}

type TransferDataProductLabel struct {
	IsActive bool `json:"IsActive"`
	IsChildFromParentWithLabel bool `json:"IsChildFromParentWithLabel"`
	IsDiscontinued bool `json:"IsDiscontinued"`
	LastLabelGenerationDate *string `json:"LastLabelGenerationDate"`
	PackageId *int `json:"PackageId"`
	QrCount int `json:"QrCount"`
	TagId *int `json:"TagId"`
}

type TransferProductLabel struct {
	IsActive bool `json:"IsActive"`
	IsChildFromParentWithLabel bool `json:"IsChildFromParentWithLabel"`
	IsDiscontinued bool `json:"IsDiscontinued"`
	LastLabelGenerationDate *string `json:"LastLabelGenerationDate"`
	PackageId *int `json:"PackageId"`
	QrCount int `json:"QrCount"`
	TagId *int `json:"TagId"`
}

