from typing import TypedDict, List, Optional, Any, Generic, TypeVar, TYPE_CHECKING
from typing_extensions import TypedDict

if TYPE_CHECKING:
    from . import *

class PlantWastePackage(TypedDict, total=False):
    ArchivedDate: str
    ContainsDecontaminatedProduct: bool
    ContainsRemediatedProduct: bool
    DecontaminationDate: str
    ExpirationDate: str
    ExternalId: int
    FinishedDate: str
    Id: int
    InitialLabTestingState: str
    IsDonation: bool
    IsDonationPersistent: bool
    IsFinished: bool
    IsOnHold: bool
    IsOnHoldCombined: bool
    IsOnInvestigation: bool
    IsOnInvestigationHold: bool
    IsOnInvestigationRecall: bool
    IsOnRecall: bool
    IsOnRecallCombined: bool
    IsOnRetailerDelivery: bool
    IsProcessValidationTestingSample: bool
    IsProductionBatch: bool
    IsTestingSample: bool
    IsTradeSample: bool
    IsTradeSamplePersistent: bool
    Item: 'PlantsPlantWastePackageItem'
    ItemFromFacilityLicenseNumber: str
    ItemFromFacilityName: str
    LabTestResultExpirationDateTime: str
    LabTestStage: str
    LabTestStageId: int
    LabTestingPerformedDate: str
    LabTestingRecordedDate: str
    LabTestingState: str
    LabTestingStateDate: str
    Label: str
    LabelsLastGeneratedDateTime: str
    LastModified: str
    LocationId: int
    LocationName: str
    LocationTypeName: str
    Note: str
    OriginalPackageQuantity: float
    PackageForProductDestruction: str
    PackageType: str
    PackagedDate: str
    PatientLicenseNumber: str
    ProductLabel: 'PlantsPlantWastePackageProductLabel'
    ProductRequiresDecontamination: bool
    ProductRequiresRemediation: bool
    ProductionBatchNumber: str
    Quantity: float
    ReceivedDateTime: str
    ReceivedFromFacilityLicenseNumber: str
    ReceivedFromFacilityName: str
    ReceivedFromManifestNumber: str
    RemediationDate: str
    SellByDate: str
    SourceHarvestCount: int
    SourceHarvestNames: str
    SourcePackageCount: int
    SourcePackageIsDonation: bool
    SourcePackageIsTradeSample: bool
    SourcePackageLabels: str
    SourceProcessingJobCount: int
    SourceProductionBatchNumbers: str
    SublocationId: int
    SublocationName: str
    UnitOfMeasureAbbreviation: str
    UnitOfMeasureName: str
    UseByDate: str
