package models

type Facility struct {
	Alias string `json:"Alias"`
	AllowTransferOfOnHoldPackages *bool `json:"AllowTransferOfOnHoldPackages"`
	AllowTransferOfOnRecallPackages *bool `json:"AllowTransferOfOnRecallPackages"`
	CredentialedDate string `json:"CredentialedDate"`
	DisplayName string `json:"DisplayName"`
	Email *string `json:"Email"`
	FacilityId int `json:"FacilityId"`
	FacilityType FacilityType `json:"FacilityType"`
	HireDate string `json:"HireDate"`
	IsFinancialContact bool `json:"IsFinancialContact"`
	IsManager bool `json:"IsManager"`
	IsOwner bool `json:"IsOwner"`
	License FacilityLicense `json:"License"`
	Name string `json:"Name"`
	Occupations []interface{} `json:"Occupations"`
	SupportActivationDate *string `json:"SupportActivationDate"`
	SupportExpirationDate *string `json:"SupportExpirationDate"`
}

type FacilityLicense struct {
	EmployeeLicenseNumber string `json:"EmployeeLicenseNumber"`
	EndDate string `json:"EndDate"`
	LicenseType string `json:"LicenseType"`
	Number string `json:"Number"`
	StartDate string `json:"StartDate"`
}

type FacilityType struct {
	AdvancedSales bool `json:"AdvancedSales"`
	CanAccessCatalog bool `json:"CanAccessCatalog"`
	CanAdjustSourcePackagesWithPartials bool `json:"CanAdjustSourcePackagesWithPartials"`
	CanAssignLocationsToPackages bool `json:"CanAssignLocationsToPackages"`
	CanAssignLocationsToPlantBatches bool `json:"CanAssignLocationsToPlantBatches"`
	CanClonePlantBatches bool `json:"CanClonePlantBatches"`
	CanCreateDerivedPackages bool `json:"CanCreateDerivedPackages"`
	CanCreateImmaturePlantPackagesFromPlants bool `json:"CanCreateImmaturePlantPackagesFromPlants"`
	CanCreateOpeningBalancePackages bool `json:"CanCreateOpeningBalancePackages"`
	CanCreateOpeningBalancePlantBatches bool `json:"CanCreateOpeningBalancePlantBatches"`
	CanCreatePartialPackages bool `json:"CanCreatePartialPackages"`
	CanCreateProcessValidationPackages bool `json:"CanCreateProcessValidationPackages"`
	CanCreateTradeSamplePackages bool `json:"CanCreateTradeSamplePackages"`
	CanDecontaminatePackagesWithFailedLabResults bool `json:"CanDecontaminatePackagesWithFailedLabResults"`
	CanDeliverSalesToConsumers bool `json:"CanDeliverSalesToConsumers"`
	CanDeliverSalesToPatients bool `json:"CanDeliverSalesToPatients"`
	CanDestroyProduct bool `json:"CanDestroyProduct"`
	CanDonatePackages bool `json:"CanDonatePackages"`
	CanDownloadProductLabel bool `json:"CanDownloadProductLabel"`
	CanGrowPlants bool `json:"CanGrowPlants"`
	CanHaveMemberPatients bool `json:"CanHaveMemberPatients"`
	CanInfuseProducts bool `json:"CanInfuseProducts"`
	CanManageItemBrands bool `json:"CanManageItemBrands"`
	CanPackageVegetativePlants bool `json:"CanPackageVegetativePlants"`
	CanPackageWaste bool `json:"CanPackageWaste"`
	CanReceiveAssociateProductLabel bool `json:"CanReceiveAssociateProductLabel"`
	CanRecordProcessingJobs bool `json:"CanRecordProcessingJobs"`
	CanRecordProductForDestruction bool `json:"CanRecordProductForDestruction"`
	CanRemediatePackagesWithFailedLabResults bool `json:"CanRemediatePackagesWithFailedLabResults"`
	CanReportAdulteration bool `json:"CanReportAdulteration"`
	CanReportHarvestSchedules bool `json:"CanReportHarvestSchedules"`
	CanReportOperationalExceptions bool `json:"CanReportOperationalExceptions"`
	CanReportPatientCheckIns bool `json:"CanReportPatientCheckIns"`
	CanReportPatientsAdverseResponses bool `json:"CanReportPatientsAdverseResponses"`
	CanReportStrainProperties bool `json:"CanReportStrainProperties"`
	CanRequestProductDecontamination bool `json:"CanRequestProductDecontamination"`
	CanRequestProductRemediation bool `json:"CanRequestProductRemediation"`
	CanRequireHarvestSampleLabTestBatches bool `json:"CanRequireHarvestSampleLabTestBatches"`
	CanRequirePackageSampleLabTestBatches bool `json:"CanRequirePackageSampleLabTestBatches"`
	CanReturnPackageQuantity bool `json:"CanReturnPackageQuantity"`
	CanSellToCaregivers bool `json:"CanSellToCaregivers"`
	CanSellToConsumers bool `json:"CanSellToConsumers"`
	CanSellToExternalPatients bool `json:"CanSellToExternalPatients"`
	CanSellToPatients bool `json:"CanSellToPatients"`
	CanSpecifyPatientSalesLimitExemption bool `json:"CanSpecifyPatientSalesLimitExemption"`
	CanSubmitHarvestsForTesting bool `json:"CanSubmitHarvestsForTesting"`
	CanSubmitPackagesForTesting bool `json:"CanSubmitPackagesForTesting"`
	CanTagPlantBatches bool `json:"CanTagPlantBatches"`
	CanTestPackages bool `json:"CanTestPackages"`
	CanTrackMotherPlantsAsGrowthPhase bool `json:"CanTrackMotherPlantsAsGrowthPhase"`
	CanTrackVegetativePlants bool `json:"CanTrackVegetativePlants"`
	CanTransferFromExternalFacilities bool `json:"CanTransferFromExternalFacilities"`
	CanUpdateLocationsOnPackages bool `json:"CanUpdateLocationsOnPackages"`
	CanUpdatePlantStrains bool `json:"CanUpdatePlantStrains"`
	CanUseComplianceLabel bool `json:"CanUseComplianceLabel"`
	CanViewSourcePackages bool `json:"CanViewSourcePackages"`
	DeliverySalesToNonResidentConsumer bool `json:"DeliverySalesToNonResidentConsumer"`
	EnableExternalIdentifier bool `json:"EnableExternalIdentifier"`
	EnableSublocations bool `json:"EnableSublocations"`
	IsHemp bool `json:"IsHemp"`
	IsMedical bool `json:"IsMedical"`
	IsRetail bool `json:"IsRetail"`
	IsSalesDeliveryHub bool `json:"IsSalesDeliveryHub"`
	PackagesRequirePatientAffiliation bool `json:"PackagesRequirePatientAffiliation"`
	PlantBatchesCanContainMotherPlants bool `json:"PlantBatchesCanContainMotherPlants"`
	PlantsRequirePatientAffiliation bool `json:"PlantsRequirePatientAffiliation"`
	RestrictHarvestPlantRestoreTimeHours *int `json:"RestrictHarvestPlantRestoreTimeHours"`
	RestrictPlantBatchAdjustmentTimeHours *int `json:"RestrictPlantBatchAdjustmentTimeHours"`
	RestrictWholesalePriceEditDays *int `json:"RestrictWholesalePriceEditDays"`
	RetailSalesToNonResidentConsumer bool `json:"RetailSalesToNonResidentConsumer"`
	RetailerDelivery bool `json:"RetailerDelivery"`
	RetailerDeliveryAllowDonations bool `json:"RetailerDeliveryAllowDonations"`
	RetailerDeliveryAllowPartialPackages bool `json:"RetailerDeliveryAllowPartialPackages"`
	RetailerDeliveryAllowTradeSamples bool `json:"RetailerDeliveryAllowTradeSamples"`
	RetailerDeliveryRequirePrice bool `json:"RetailerDeliveryRequirePrice"`
	SalesDeliveryAllowAddress bool `json:"SalesDeliveryAllowAddress"`
	SalesDeliveryAllowCity bool `json:"SalesDeliveryAllowCity"`
	SalesDeliveryAllowCounty bool `json:"SalesDeliveryAllowCounty"`
	SalesDeliveryAllowPlannedRoute bool `json:"SalesDeliveryAllowPlannedRoute"`
	SalesDeliveryAllowState bool `json:"SalesDeliveryAllowState"`
	SalesDeliveryAllowZip bool `json:"SalesDeliveryAllowZip"`
	SalesDeliveryRequireConsumerId bool `json:"SalesDeliveryRequireConsumerId"`
	SalesDeliveryRequirePatientNumber bool `json:"SalesDeliveryRequirePatientNumber"`
	SalesDeliveryRequireRecipientName bool `json:"SalesDeliveryRequireRecipientName"`
	SalesDeliveryRequireZone bool `json:"SalesDeliveryRequireZone"`
	SalesRequireCaregiverNumber bool `json:"SalesRequireCaregiverNumber"`
	SalesRequireCaregiverPatientNumber bool `json:"SalesRequireCaregiverPatientNumber"`
	SalesRequireExternalPatientIdentificationMethod bool `json:"SalesRequireExternalPatientIdentificationMethod"`
	SalesRequireExternalPatientNumber bool `json:"SalesRequireExternalPatientNumber"`
	SalesRequirePatientNumber bool `json:"SalesRequirePatientNumber"`
	TaxExemptReportingFeesFacilityType bool `json:"TaxExemptReportingFeesFacilityType"`
	TaxExemptTagOrdersFacilityType bool `json:"TaxExemptTagOrdersFacilityType"`
	TestsRequireLabSample bool `json:"TestsRequireLabSample"`
	TotalMemberPatientsAllowed *int `json:"TotalMemberPatientsAllowed"`
}
